// Generated by skills/hht_website/scripts/build_week_calendar.py — do not
// hand-edit. Source: the client's official workbook
// "Spicebush & Swallowtail Weeks (for Owned Units)" (2026-2040),
// archived at skills/hht_website/references/. 2025 is retained from the
// earlier official 2025-2029 PDF.
//
// Weeks run Friday-to-Friday and shift each calendar year. Years with 53
// weeks: 2027, 2032, 2038. Late weeks fall in the following
// January (week 52 of 2025 is 2026-01-02), so `year` is the week-year label,
// not the year of the date.

export interface WeekDate {
  weekNumber: number;
  year: number;
  startDate: string; // ISO date
  endDate: string; // ISO date
}

const WEEK_CALENDAR: WeekDate[] = [
  { weekNumber: 1, year: 2025, startDate: "2025-01-10", endDate: "2025-01-17" },
  { weekNumber: 1, year: 2026, startDate: "2026-01-09", endDate: "2026-01-16" },
  { weekNumber: 1, year: 2027, startDate: "2027-01-08", endDate: "2027-01-15" },
  { weekNumber: 1, year: 2028, startDate: "2028-01-14", endDate: "2028-01-21" },
  { weekNumber: 1, year: 2029, startDate: "2029-01-12", endDate: "2029-01-19" },
  { weekNumber: 1, year: 2030, startDate: "2030-01-11", endDate: "2030-01-18" },
  { weekNumber: 1, year: 2031, startDate: "2031-01-10", endDate: "2031-01-17" },
  { weekNumber: 1, year: 2032, startDate: "2032-01-09", endDate: "2032-01-16" },
  { weekNumber: 1, year: 2033, startDate: "2033-01-14", endDate: "2033-01-21" },
  { weekNumber: 1, year: 2034, startDate: "2034-01-13", endDate: "2034-01-20" },
  { weekNumber: 1, year: 2035, startDate: "2035-01-12", endDate: "2035-01-19" },
  { weekNumber: 1, year: 2036, startDate: "2036-01-11", endDate: "2036-01-18" },
  { weekNumber: 1, year: 2037, startDate: "2037-01-09", endDate: "2037-01-16" },
  { weekNumber: 1, year: 2038, startDate: "2038-01-08", endDate: "2038-01-15" },
  { weekNumber: 1, year: 2039, startDate: "2039-01-14", endDate: "2039-01-21" },
  { weekNumber: 1, year: 2040, startDate: "2040-01-13", endDate: "2040-01-20" },
  { weekNumber: 2, year: 2025, startDate: "2025-01-17", endDate: "2025-01-24" },
  { weekNumber: 2, year: 2026, startDate: "2026-01-16", endDate: "2026-01-23" },
  { weekNumber: 2, year: 2027, startDate: "2027-01-15", endDate: "2027-01-22" },
  { weekNumber: 2, year: 2028, startDate: "2028-01-21", endDate: "2028-01-28" },
  { weekNumber: 2, year: 2029, startDate: "2029-01-19", endDate: "2029-01-26" },
  { weekNumber: 2, year: 2030, startDate: "2030-01-18", endDate: "2030-01-25" },
  { weekNumber: 2, year: 2031, startDate: "2031-01-17", endDate: "2031-01-24" },
  { weekNumber: 2, year: 2032, startDate: "2032-01-16", endDate: "2032-01-23" },
  { weekNumber: 2, year: 2033, startDate: "2033-01-21", endDate: "2033-01-28" },
  { weekNumber: 2, year: 2034, startDate: "2034-01-20", endDate: "2034-01-27" },
  { weekNumber: 2, year: 2035, startDate: "2035-01-19", endDate: "2035-01-26" },
  { weekNumber: 2, year: 2036, startDate: "2036-01-18", endDate: "2036-01-25" },
  { weekNumber: 2, year: 2037, startDate: "2037-01-16", endDate: "2037-01-23" },
  { weekNumber: 2, year: 2038, startDate: "2038-01-15", endDate: "2038-01-22" },
  { weekNumber: 2, year: 2039, startDate: "2039-01-21", endDate: "2039-01-28" },
  { weekNumber: 2, year: 2040, startDate: "2040-01-20", endDate: "2040-01-27" },
  { weekNumber: 3, year: 2025, startDate: "2025-01-24", endDate: "2025-01-31" },
  { weekNumber: 3, year: 2026, startDate: "2026-01-23", endDate: "2026-01-30" },
  { weekNumber: 3, year: 2027, startDate: "2027-01-22", endDate: "2027-01-29" },
  { weekNumber: 3, year: 2028, startDate: "2028-01-28", endDate: "2028-02-04" },
  { weekNumber: 3, year: 2029, startDate: "2029-01-26", endDate: "2029-02-02" },
  { weekNumber: 3, year: 2030, startDate: "2030-01-25", endDate: "2030-02-01" },
  { weekNumber: 3, year: 2031, startDate: "2031-01-24", endDate: "2031-01-31" },
  { weekNumber: 3, year: 2032, startDate: "2032-01-23", endDate: "2032-01-30" },
  { weekNumber: 3, year: 2033, startDate: "2033-01-28", endDate: "2033-02-04" },
  { weekNumber: 3, year: 2034, startDate: "2034-01-27", endDate: "2034-02-03" },
  { weekNumber: 3, year: 2035, startDate: "2035-01-26", endDate: "2035-02-02" },
  { weekNumber: 3, year: 2036, startDate: "2036-01-25", endDate: "2036-02-01" },
  { weekNumber: 3, year: 2037, startDate: "2037-01-23", endDate: "2037-01-30" },
  { weekNumber: 3, year: 2038, startDate: "2038-01-22", endDate: "2038-01-29" },
  { weekNumber: 3, year: 2039, startDate: "2039-01-28", endDate: "2039-02-04" },
  { weekNumber: 3, year: 2040, startDate: "2040-01-27", endDate: "2040-02-03" },
  { weekNumber: 4, year: 2025, startDate: "2025-01-31", endDate: "2025-02-07" },
  { weekNumber: 4, year: 2026, startDate: "2026-01-30", endDate: "2026-02-06" },
  { weekNumber: 4, year: 2027, startDate: "2027-01-29", endDate: "2027-02-05" },
  { weekNumber: 4, year: 2028, startDate: "2028-02-04", endDate: "2028-02-11" },
  { weekNumber: 4, year: 2029, startDate: "2029-02-02", endDate: "2029-02-09" },
  { weekNumber: 4, year: 2030, startDate: "2030-02-01", endDate: "2030-02-08" },
  { weekNumber: 4, year: 2031, startDate: "2031-01-31", endDate: "2031-02-07" },
  { weekNumber: 4, year: 2032, startDate: "2032-01-30", endDate: "2032-02-06" },
  { weekNumber: 4, year: 2033, startDate: "2033-02-04", endDate: "2033-02-11" },
  { weekNumber: 4, year: 2034, startDate: "2034-02-03", endDate: "2034-02-10" },
  { weekNumber: 4, year: 2035, startDate: "2035-02-02", endDate: "2035-02-09" },
  { weekNumber: 4, year: 2036, startDate: "2036-02-01", endDate: "2036-02-08" },
  { weekNumber: 4, year: 2037, startDate: "2037-01-30", endDate: "2037-02-06" },
  { weekNumber: 4, year: 2038, startDate: "2038-01-29", endDate: "2038-02-05" },
  { weekNumber: 4, year: 2039, startDate: "2039-02-04", endDate: "2039-02-11" },
  { weekNumber: 4, year: 2040, startDate: "2040-02-03", endDate: "2040-02-10" },
  { weekNumber: 5, year: 2025, startDate: "2025-02-07", endDate: "2025-02-14" },
  { weekNumber: 5, year: 2026, startDate: "2026-02-06", endDate: "2026-02-13" },
  { weekNumber: 5, year: 2027, startDate: "2027-02-05", endDate: "2027-02-12" },
  { weekNumber: 5, year: 2028, startDate: "2028-02-11", endDate: "2028-02-18" },
  { weekNumber: 5, year: 2029, startDate: "2029-02-09", endDate: "2029-02-16" },
  { weekNumber: 5, year: 2030, startDate: "2030-02-08", endDate: "2030-02-15" },
  { weekNumber: 5, year: 2031, startDate: "2031-02-07", endDate: "2031-02-14" },
  { weekNumber: 5, year: 2032, startDate: "2032-02-06", endDate: "2032-02-13" },
  { weekNumber: 5, year: 2033, startDate: "2033-02-11", endDate: "2033-02-18" },
  { weekNumber: 5, year: 2034, startDate: "2034-02-10", endDate: "2034-02-17" },
  { weekNumber: 5, year: 2035, startDate: "2035-02-09", endDate: "2035-02-16" },
  { weekNumber: 5, year: 2036, startDate: "2036-02-08", endDate: "2036-02-15" },
  { weekNumber: 5, year: 2037, startDate: "2037-02-06", endDate: "2037-02-13" },
  { weekNumber: 5, year: 2038, startDate: "2038-02-05", endDate: "2038-02-12" },
  { weekNumber: 5, year: 2039, startDate: "2039-02-11", endDate: "2039-02-18" },
  { weekNumber: 5, year: 2040, startDate: "2040-02-10", endDate: "2040-02-17" },
  { weekNumber: 6, year: 2025, startDate: "2025-02-14", endDate: "2025-02-21" },
  { weekNumber: 6, year: 2026, startDate: "2026-02-13", endDate: "2026-02-20" },
  { weekNumber: 6, year: 2027, startDate: "2027-02-12", endDate: "2027-02-19" },
  { weekNumber: 6, year: 2028, startDate: "2028-02-18", endDate: "2028-02-25" },
  { weekNumber: 6, year: 2029, startDate: "2029-02-16", endDate: "2029-02-23" },
  { weekNumber: 6, year: 2030, startDate: "2030-02-15", endDate: "2030-02-22" },
  { weekNumber: 6, year: 2031, startDate: "2031-02-14", endDate: "2031-02-21" },
  { weekNumber: 6, year: 2032, startDate: "2032-02-13", endDate: "2032-02-20" },
  { weekNumber: 6, year: 2033, startDate: "2033-02-18", endDate: "2033-02-25" },
  { weekNumber: 6, year: 2034, startDate: "2034-02-17", endDate: "2034-02-24" },
  { weekNumber: 6, year: 2035, startDate: "2035-02-16", endDate: "2035-02-23" },
  { weekNumber: 6, year: 2036, startDate: "2036-02-15", endDate: "2036-02-22" },
  { weekNumber: 6, year: 2037, startDate: "2037-02-13", endDate: "2037-02-20" },
  { weekNumber: 6, year: 2038, startDate: "2038-02-12", endDate: "2038-02-19" },
  { weekNumber: 6, year: 2039, startDate: "2039-02-18", endDate: "2039-02-25" },
  { weekNumber: 6, year: 2040, startDate: "2040-02-17", endDate: "2040-02-24" },
  { weekNumber: 7, year: 2025, startDate: "2025-02-21", endDate: "2025-02-28" },
  { weekNumber: 7, year: 2026, startDate: "2026-02-20", endDate: "2026-02-27" },
  { weekNumber: 7, year: 2027, startDate: "2027-02-19", endDate: "2027-02-26" },
  { weekNumber: 7, year: 2028, startDate: "2028-02-25", endDate: "2028-03-03" },
  { weekNumber: 7, year: 2029, startDate: "2029-02-23", endDate: "2029-03-02" },
  { weekNumber: 7, year: 2030, startDate: "2030-02-22", endDate: "2030-03-01" },
  { weekNumber: 7, year: 2031, startDate: "2031-02-21", endDate: "2031-02-28" },
  { weekNumber: 7, year: 2032, startDate: "2032-02-20", endDate: "2032-02-27" },
  { weekNumber: 7, year: 2033, startDate: "2033-02-25", endDate: "2033-03-04" },
  { weekNumber: 7, year: 2034, startDate: "2034-02-24", endDate: "2034-03-03" },
  { weekNumber: 7, year: 2035, startDate: "2035-02-23", endDate: "2035-03-02" },
  { weekNumber: 7, year: 2036, startDate: "2036-02-22", endDate: "2036-02-29" },
  { weekNumber: 7, year: 2037, startDate: "2037-02-20", endDate: "2037-02-27" },
  { weekNumber: 7, year: 2038, startDate: "2038-02-19", endDate: "2038-02-26" },
  { weekNumber: 7, year: 2039, startDate: "2039-02-25", endDate: "2039-03-04" },
  { weekNumber: 7, year: 2040, startDate: "2040-02-24", endDate: "2040-03-02" },
  { weekNumber: 8, year: 2025, startDate: "2025-02-28", endDate: "2025-03-07" },
  { weekNumber: 8, year: 2026, startDate: "2026-02-27", endDate: "2026-03-06" },
  { weekNumber: 8, year: 2027, startDate: "2027-02-26", endDate: "2027-03-05" },
  { weekNumber: 8, year: 2028, startDate: "2028-03-03", endDate: "2028-03-10" },
  { weekNumber: 8, year: 2029, startDate: "2029-03-02", endDate: "2029-03-09" },
  { weekNumber: 8, year: 2030, startDate: "2030-03-01", endDate: "2030-03-08" },
  { weekNumber: 8, year: 2031, startDate: "2031-02-28", endDate: "2031-03-07" },
  { weekNumber: 8, year: 2032, startDate: "2032-02-27", endDate: "2032-03-05" },
  { weekNumber: 8, year: 2033, startDate: "2033-03-04", endDate: "2033-03-11" },
  { weekNumber: 8, year: 2034, startDate: "2034-03-03", endDate: "2034-03-10" },
  { weekNumber: 8, year: 2035, startDate: "2035-03-02", endDate: "2035-03-09" },
  { weekNumber: 8, year: 2036, startDate: "2036-02-29", endDate: "2036-03-07" },
  { weekNumber: 8, year: 2037, startDate: "2037-02-27", endDate: "2037-03-06" },
  { weekNumber: 8, year: 2038, startDate: "2038-02-26", endDate: "2038-03-05" },
  { weekNumber: 8, year: 2039, startDate: "2039-03-04", endDate: "2039-03-11" },
  { weekNumber: 8, year: 2040, startDate: "2040-03-02", endDate: "2040-03-09" },
  { weekNumber: 9, year: 2025, startDate: "2025-03-07", endDate: "2025-03-14" },
  { weekNumber: 9, year: 2026, startDate: "2026-03-06", endDate: "2026-03-13" },
  { weekNumber: 9, year: 2027, startDate: "2027-03-05", endDate: "2027-03-12" },
  { weekNumber: 9, year: 2028, startDate: "2028-03-10", endDate: "2028-03-17" },
  { weekNumber: 9, year: 2029, startDate: "2029-03-09", endDate: "2029-03-16" },
  { weekNumber: 9, year: 2030, startDate: "2030-03-08", endDate: "2030-03-15" },
  { weekNumber: 9, year: 2031, startDate: "2031-03-07", endDate: "2031-03-14" },
  { weekNumber: 9, year: 2032, startDate: "2032-03-05", endDate: "2032-03-12" },
  { weekNumber: 9, year: 2033, startDate: "2033-03-11", endDate: "2033-03-18" },
  { weekNumber: 9, year: 2034, startDate: "2034-03-10", endDate: "2034-03-17" },
  { weekNumber: 9, year: 2035, startDate: "2035-03-09", endDate: "2035-03-16" },
  { weekNumber: 9, year: 2036, startDate: "2036-03-07", endDate: "2036-03-14" },
  { weekNumber: 9, year: 2037, startDate: "2037-03-06", endDate: "2037-03-13" },
  { weekNumber: 9, year: 2038, startDate: "2038-03-05", endDate: "2038-03-12" },
  { weekNumber: 9, year: 2039, startDate: "2039-03-11", endDate: "2039-03-18" },
  { weekNumber: 9, year: 2040, startDate: "2040-03-09", endDate: "2040-03-16" },
  {
    weekNumber: 10,
    year: 2025,
    startDate: "2025-03-14",
    endDate: "2025-03-21",
  },
  {
    weekNumber: 10,
    year: 2026,
    startDate: "2026-03-13",
    endDate: "2026-03-20",
  },
  {
    weekNumber: 10,
    year: 2027,
    startDate: "2027-03-12",
    endDate: "2027-03-19",
  },
  {
    weekNumber: 10,
    year: 2028,
    startDate: "2028-03-17",
    endDate: "2028-03-24",
  },
  {
    weekNumber: 10,
    year: 2029,
    startDate: "2029-03-16",
    endDate: "2029-03-23",
  },
  {
    weekNumber: 10,
    year: 2030,
    startDate: "2030-03-15",
    endDate: "2030-03-22",
  },
  {
    weekNumber: 10,
    year: 2031,
    startDate: "2031-03-14",
    endDate: "2031-03-21",
  },
  {
    weekNumber: 10,
    year: 2032,
    startDate: "2032-03-12",
    endDate: "2032-03-19",
  },
  {
    weekNumber: 10,
    year: 2033,
    startDate: "2033-03-18",
    endDate: "2033-03-25",
  },
  {
    weekNumber: 10,
    year: 2034,
    startDate: "2034-03-17",
    endDate: "2034-03-24",
  },
  {
    weekNumber: 10,
    year: 2035,
    startDate: "2035-03-16",
    endDate: "2035-03-23",
  },
  {
    weekNumber: 10,
    year: 2036,
    startDate: "2036-03-14",
    endDate: "2036-03-21",
  },
  {
    weekNumber: 10,
    year: 2037,
    startDate: "2037-03-13",
    endDate: "2037-03-20",
  },
  {
    weekNumber: 10,
    year: 2038,
    startDate: "2038-03-12",
    endDate: "2038-03-19",
  },
  {
    weekNumber: 10,
    year: 2039,
    startDate: "2039-03-18",
    endDate: "2039-03-25",
  },
  {
    weekNumber: 10,
    year: 2040,
    startDate: "2040-03-16",
    endDate: "2040-03-23",
  },
  {
    weekNumber: 11,
    year: 2025,
    startDate: "2025-03-21",
    endDate: "2025-03-28",
  },
  {
    weekNumber: 11,
    year: 2026,
    startDate: "2026-03-20",
    endDate: "2026-03-27",
  },
  {
    weekNumber: 11,
    year: 2027,
    startDate: "2027-03-19",
    endDate: "2027-03-26",
  },
  {
    weekNumber: 11,
    year: 2028,
    startDate: "2028-03-24",
    endDate: "2028-03-31",
  },
  {
    weekNumber: 11,
    year: 2029,
    startDate: "2029-03-23",
    endDate: "2029-03-30",
  },
  {
    weekNumber: 11,
    year: 2030,
    startDate: "2030-03-22",
    endDate: "2030-03-29",
  },
  {
    weekNumber: 11,
    year: 2031,
    startDate: "2031-03-21",
    endDate: "2031-03-28",
  },
  {
    weekNumber: 11,
    year: 2032,
    startDate: "2032-03-19",
    endDate: "2032-03-26",
  },
  {
    weekNumber: 11,
    year: 2033,
    startDate: "2033-03-25",
    endDate: "2033-04-01",
  },
  {
    weekNumber: 11,
    year: 2034,
    startDate: "2034-03-24",
    endDate: "2034-03-31",
  },
  {
    weekNumber: 11,
    year: 2035,
    startDate: "2035-03-23",
    endDate: "2035-03-30",
  },
  {
    weekNumber: 11,
    year: 2036,
    startDate: "2036-03-21",
    endDate: "2036-03-28",
  },
  {
    weekNumber: 11,
    year: 2037,
    startDate: "2037-03-20",
    endDate: "2037-03-27",
  },
  {
    weekNumber: 11,
    year: 2038,
    startDate: "2038-03-19",
    endDate: "2038-03-26",
  },
  {
    weekNumber: 11,
    year: 2039,
    startDate: "2039-03-25",
    endDate: "2039-04-01",
  },
  {
    weekNumber: 11,
    year: 2040,
    startDate: "2040-03-23",
    endDate: "2040-03-30",
  },
  {
    weekNumber: 12,
    year: 2025,
    startDate: "2025-03-28",
    endDate: "2025-04-04",
  },
  {
    weekNumber: 12,
    year: 2026,
    startDate: "2026-03-27",
    endDate: "2026-04-03",
  },
  {
    weekNumber: 12,
    year: 2027,
    startDate: "2027-03-26",
    endDate: "2027-04-02",
  },
  {
    weekNumber: 12,
    year: 2028,
    startDate: "2028-03-31",
    endDate: "2028-04-07",
  },
  {
    weekNumber: 12,
    year: 2029,
    startDate: "2029-03-30",
    endDate: "2029-04-06",
  },
  {
    weekNumber: 12,
    year: 2030,
    startDate: "2030-03-29",
    endDate: "2030-04-05",
  },
  {
    weekNumber: 12,
    year: 2031,
    startDate: "2031-03-28",
    endDate: "2031-04-04",
  },
  {
    weekNumber: 12,
    year: 2032,
    startDate: "2032-03-26",
    endDate: "2032-04-02",
  },
  {
    weekNumber: 12,
    year: 2033,
    startDate: "2033-04-01",
    endDate: "2033-04-08",
  },
  {
    weekNumber: 12,
    year: 2034,
    startDate: "2034-03-31",
    endDate: "2034-04-07",
  },
  {
    weekNumber: 12,
    year: 2035,
    startDate: "2035-03-30",
    endDate: "2035-04-06",
  },
  {
    weekNumber: 12,
    year: 2036,
    startDate: "2036-03-28",
    endDate: "2036-04-04",
  },
  {
    weekNumber: 12,
    year: 2037,
    startDate: "2037-03-27",
    endDate: "2037-04-03",
  },
  {
    weekNumber: 12,
    year: 2038,
    startDate: "2038-03-26",
    endDate: "2038-04-02",
  },
  {
    weekNumber: 12,
    year: 2039,
    startDate: "2039-04-01",
    endDate: "2039-04-08",
  },
  {
    weekNumber: 12,
    year: 2040,
    startDate: "2040-03-30",
    endDate: "2040-04-06",
  },
  {
    weekNumber: 13,
    year: 2025,
    startDate: "2025-04-04",
    endDate: "2025-04-11",
  },
  {
    weekNumber: 13,
    year: 2026,
    startDate: "2026-04-03",
    endDate: "2026-04-10",
  },
  {
    weekNumber: 13,
    year: 2027,
    startDate: "2027-04-02",
    endDate: "2027-04-09",
  },
  {
    weekNumber: 13,
    year: 2028,
    startDate: "2028-04-07",
    endDate: "2028-04-14",
  },
  {
    weekNumber: 13,
    year: 2029,
    startDate: "2029-04-06",
    endDate: "2029-04-13",
  },
  {
    weekNumber: 13,
    year: 2030,
    startDate: "2030-04-05",
    endDate: "2030-04-12",
  },
  {
    weekNumber: 13,
    year: 2031,
    startDate: "2031-04-04",
    endDate: "2031-04-11",
  },
  {
    weekNumber: 13,
    year: 2032,
    startDate: "2032-04-02",
    endDate: "2032-04-09",
  },
  {
    weekNumber: 13,
    year: 2033,
    startDate: "2033-04-08",
    endDate: "2033-04-15",
  },
  {
    weekNumber: 13,
    year: 2034,
    startDate: "2034-04-07",
    endDate: "2034-04-14",
  },
  {
    weekNumber: 13,
    year: 2035,
    startDate: "2035-04-06",
    endDate: "2035-04-13",
  },
  {
    weekNumber: 13,
    year: 2036,
    startDate: "2036-04-04",
    endDate: "2036-04-11",
  },
  {
    weekNumber: 13,
    year: 2037,
    startDate: "2037-04-03",
    endDate: "2037-04-10",
  },
  {
    weekNumber: 13,
    year: 2038,
    startDate: "2038-04-02",
    endDate: "2038-04-09",
  },
  {
    weekNumber: 13,
    year: 2039,
    startDate: "2039-04-08",
    endDate: "2039-04-15",
  },
  {
    weekNumber: 13,
    year: 2040,
    startDate: "2040-04-06",
    endDate: "2040-04-13",
  },
  {
    weekNumber: 14,
    year: 2025,
    startDate: "2025-04-11",
    endDate: "2025-04-18",
  },
  {
    weekNumber: 14,
    year: 2026,
    startDate: "2026-04-10",
    endDate: "2026-04-17",
  },
  {
    weekNumber: 14,
    year: 2027,
    startDate: "2027-04-09",
    endDate: "2027-04-16",
  },
  {
    weekNumber: 14,
    year: 2028,
    startDate: "2028-04-14",
    endDate: "2028-04-21",
  },
  {
    weekNumber: 14,
    year: 2029,
    startDate: "2029-04-13",
    endDate: "2029-04-20",
  },
  {
    weekNumber: 14,
    year: 2030,
    startDate: "2030-04-12",
    endDate: "2030-04-19",
  },
  {
    weekNumber: 14,
    year: 2031,
    startDate: "2031-04-11",
    endDate: "2031-04-18",
  },
  {
    weekNumber: 14,
    year: 2032,
    startDate: "2032-04-09",
    endDate: "2032-04-16",
  },
  {
    weekNumber: 14,
    year: 2033,
    startDate: "2033-04-15",
    endDate: "2033-04-22",
  },
  {
    weekNumber: 14,
    year: 2034,
    startDate: "2034-04-14",
    endDate: "2034-04-21",
  },
  {
    weekNumber: 14,
    year: 2035,
    startDate: "2035-04-13",
    endDate: "2035-04-20",
  },
  {
    weekNumber: 14,
    year: 2036,
    startDate: "2036-04-11",
    endDate: "2036-04-18",
  },
  {
    weekNumber: 14,
    year: 2037,
    startDate: "2037-04-10",
    endDate: "2037-04-17",
  },
  {
    weekNumber: 14,
    year: 2038,
    startDate: "2038-04-09",
    endDate: "2038-04-16",
  },
  {
    weekNumber: 14,
    year: 2039,
    startDate: "2039-04-15",
    endDate: "2039-04-22",
  },
  {
    weekNumber: 14,
    year: 2040,
    startDate: "2040-04-13",
    endDate: "2040-04-20",
  },
  {
    weekNumber: 15,
    year: 2025,
    startDate: "2025-04-18",
    endDate: "2025-04-25",
  },
  {
    weekNumber: 15,
    year: 2026,
    startDate: "2026-04-17",
    endDate: "2026-04-24",
  },
  {
    weekNumber: 15,
    year: 2027,
    startDate: "2027-04-16",
    endDate: "2027-04-23",
  },
  {
    weekNumber: 15,
    year: 2028,
    startDate: "2028-04-21",
    endDate: "2028-04-28",
  },
  {
    weekNumber: 15,
    year: 2029,
    startDate: "2029-04-20",
    endDate: "2029-04-27",
  },
  {
    weekNumber: 15,
    year: 2030,
    startDate: "2030-04-19",
    endDate: "2030-04-26",
  },
  {
    weekNumber: 15,
    year: 2031,
    startDate: "2031-04-18",
    endDate: "2031-04-25",
  },
  {
    weekNumber: 15,
    year: 2032,
    startDate: "2032-04-16",
    endDate: "2032-04-23",
  },
  {
    weekNumber: 15,
    year: 2033,
    startDate: "2033-04-22",
    endDate: "2033-04-29",
  },
  {
    weekNumber: 15,
    year: 2034,
    startDate: "2034-04-21",
    endDate: "2034-04-28",
  },
  {
    weekNumber: 15,
    year: 2035,
    startDate: "2035-04-20",
    endDate: "2035-04-27",
  },
  {
    weekNumber: 15,
    year: 2036,
    startDate: "2036-04-18",
    endDate: "2036-04-25",
  },
  {
    weekNumber: 15,
    year: 2037,
    startDate: "2037-04-17",
    endDate: "2037-04-24",
  },
  {
    weekNumber: 15,
    year: 2038,
    startDate: "2038-04-16",
    endDate: "2038-04-23",
  },
  {
    weekNumber: 15,
    year: 2039,
    startDate: "2039-04-22",
    endDate: "2039-04-29",
  },
  {
    weekNumber: 15,
    year: 2040,
    startDate: "2040-04-20",
    endDate: "2040-04-27",
  },
  {
    weekNumber: 16,
    year: 2025,
    startDate: "2025-04-25",
    endDate: "2025-05-02",
  },
  {
    weekNumber: 16,
    year: 2026,
    startDate: "2026-04-24",
    endDate: "2026-05-01",
  },
  {
    weekNumber: 16,
    year: 2027,
    startDate: "2027-04-23",
    endDate: "2027-04-30",
  },
  {
    weekNumber: 16,
    year: 2028,
    startDate: "2028-04-28",
    endDate: "2028-05-05",
  },
  {
    weekNumber: 16,
    year: 2029,
    startDate: "2029-04-27",
    endDate: "2029-05-04",
  },
  {
    weekNumber: 16,
    year: 2030,
    startDate: "2030-04-26",
    endDate: "2030-05-03",
  },
  {
    weekNumber: 16,
    year: 2031,
    startDate: "2031-04-25",
    endDate: "2031-05-02",
  },
  {
    weekNumber: 16,
    year: 2032,
    startDate: "2032-04-23",
    endDate: "2032-04-30",
  },
  {
    weekNumber: 16,
    year: 2033,
    startDate: "2033-04-29",
    endDate: "2033-05-06",
  },
  {
    weekNumber: 16,
    year: 2034,
    startDate: "2034-04-28",
    endDate: "2034-05-05",
  },
  {
    weekNumber: 16,
    year: 2035,
    startDate: "2035-04-27",
    endDate: "2035-05-04",
  },
  {
    weekNumber: 16,
    year: 2036,
    startDate: "2036-04-25",
    endDate: "2036-05-02",
  },
  {
    weekNumber: 16,
    year: 2037,
    startDate: "2037-04-24",
    endDate: "2037-05-01",
  },
  {
    weekNumber: 16,
    year: 2038,
    startDate: "2038-04-23",
    endDate: "2038-04-30",
  },
  {
    weekNumber: 16,
    year: 2039,
    startDate: "2039-04-29",
    endDate: "2039-05-06",
  },
  {
    weekNumber: 16,
    year: 2040,
    startDate: "2040-04-27",
    endDate: "2040-05-04",
  },
  {
    weekNumber: 17,
    year: 2025,
    startDate: "2025-05-02",
    endDate: "2025-05-09",
  },
  {
    weekNumber: 17,
    year: 2026,
    startDate: "2026-05-01",
    endDate: "2026-05-08",
  },
  {
    weekNumber: 17,
    year: 2027,
    startDate: "2027-04-30",
    endDate: "2027-05-07",
  },
  {
    weekNumber: 17,
    year: 2028,
    startDate: "2028-05-05",
    endDate: "2028-05-12",
  },
  {
    weekNumber: 17,
    year: 2029,
    startDate: "2029-05-04",
    endDate: "2029-05-11",
  },
  {
    weekNumber: 17,
    year: 2030,
    startDate: "2030-05-03",
    endDate: "2030-05-10",
  },
  {
    weekNumber: 17,
    year: 2031,
    startDate: "2031-05-02",
    endDate: "2031-05-09",
  },
  {
    weekNumber: 17,
    year: 2032,
    startDate: "2032-04-30",
    endDate: "2032-05-07",
  },
  {
    weekNumber: 17,
    year: 2033,
    startDate: "2033-05-06",
    endDate: "2033-05-13",
  },
  {
    weekNumber: 17,
    year: 2034,
    startDate: "2034-05-05",
    endDate: "2034-05-12",
  },
  {
    weekNumber: 17,
    year: 2035,
    startDate: "2035-05-04",
    endDate: "2035-05-11",
  },
  {
    weekNumber: 17,
    year: 2036,
    startDate: "2036-05-02",
    endDate: "2036-05-09",
  },
  {
    weekNumber: 17,
    year: 2037,
    startDate: "2037-05-01",
    endDate: "2037-05-08",
  },
  {
    weekNumber: 17,
    year: 2038,
    startDate: "2038-04-30",
    endDate: "2038-05-07",
  },
  {
    weekNumber: 17,
    year: 2039,
    startDate: "2039-05-06",
    endDate: "2039-05-13",
  },
  {
    weekNumber: 17,
    year: 2040,
    startDate: "2040-05-04",
    endDate: "2040-05-11",
  },
  {
    weekNumber: 18,
    year: 2025,
    startDate: "2025-05-09",
    endDate: "2025-05-16",
  },
  {
    weekNumber: 18,
    year: 2026,
    startDate: "2026-05-08",
    endDate: "2026-05-15",
  },
  {
    weekNumber: 18,
    year: 2027,
    startDate: "2027-05-07",
    endDate: "2027-05-14",
  },
  {
    weekNumber: 18,
    year: 2028,
    startDate: "2028-05-12",
    endDate: "2028-05-19",
  },
  {
    weekNumber: 18,
    year: 2029,
    startDate: "2029-05-11",
    endDate: "2029-05-18",
  },
  {
    weekNumber: 18,
    year: 2030,
    startDate: "2030-05-10",
    endDate: "2030-05-17",
  },
  {
    weekNumber: 18,
    year: 2031,
    startDate: "2031-05-09",
    endDate: "2031-05-16",
  },
  {
    weekNumber: 18,
    year: 2032,
    startDate: "2032-05-07",
    endDate: "2032-05-14",
  },
  {
    weekNumber: 18,
    year: 2033,
    startDate: "2033-05-13",
    endDate: "2033-05-20",
  },
  {
    weekNumber: 18,
    year: 2034,
    startDate: "2034-05-12",
    endDate: "2034-05-19",
  },
  {
    weekNumber: 18,
    year: 2035,
    startDate: "2035-05-11",
    endDate: "2035-05-18",
  },
  {
    weekNumber: 18,
    year: 2036,
    startDate: "2036-05-09",
    endDate: "2036-05-16",
  },
  {
    weekNumber: 18,
    year: 2037,
    startDate: "2037-05-08",
    endDate: "2037-05-15",
  },
  {
    weekNumber: 18,
    year: 2038,
    startDate: "2038-05-07",
    endDate: "2038-05-14",
  },
  {
    weekNumber: 18,
    year: 2039,
    startDate: "2039-05-13",
    endDate: "2039-05-20",
  },
  {
    weekNumber: 18,
    year: 2040,
    startDate: "2040-05-11",
    endDate: "2040-05-18",
  },
  {
    weekNumber: 19,
    year: 2025,
    startDate: "2025-05-16",
    endDate: "2025-05-23",
  },
  {
    weekNumber: 19,
    year: 2026,
    startDate: "2026-05-15",
    endDate: "2026-05-22",
  },
  {
    weekNumber: 19,
    year: 2027,
    startDate: "2027-05-14",
    endDate: "2027-05-21",
  },
  {
    weekNumber: 19,
    year: 2028,
    startDate: "2028-05-19",
    endDate: "2028-05-26",
  },
  {
    weekNumber: 19,
    year: 2029,
    startDate: "2029-05-18",
    endDate: "2029-05-25",
  },
  {
    weekNumber: 19,
    year: 2030,
    startDate: "2030-05-17",
    endDate: "2030-05-24",
  },
  {
    weekNumber: 19,
    year: 2031,
    startDate: "2031-05-16",
    endDate: "2031-05-23",
  },
  {
    weekNumber: 19,
    year: 2032,
    startDate: "2032-05-14",
    endDate: "2032-05-21",
  },
  {
    weekNumber: 19,
    year: 2033,
    startDate: "2033-05-20",
    endDate: "2033-05-27",
  },
  {
    weekNumber: 19,
    year: 2034,
    startDate: "2034-05-19",
    endDate: "2034-05-26",
  },
  {
    weekNumber: 19,
    year: 2035,
    startDate: "2035-05-18",
    endDate: "2035-05-25",
  },
  {
    weekNumber: 19,
    year: 2036,
    startDate: "2036-05-16",
    endDate: "2036-05-23",
  },
  {
    weekNumber: 19,
    year: 2037,
    startDate: "2037-05-15",
    endDate: "2037-05-22",
  },
  {
    weekNumber: 19,
    year: 2038,
    startDate: "2038-05-14",
    endDate: "2038-05-21",
  },
  {
    weekNumber: 19,
    year: 2039,
    startDate: "2039-05-20",
    endDate: "2039-05-27",
  },
  {
    weekNumber: 19,
    year: 2040,
    startDate: "2040-05-18",
    endDate: "2040-05-25",
  },
  {
    weekNumber: 20,
    year: 2025,
    startDate: "2025-05-23",
    endDate: "2025-05-30",
  },
  {
    weekNumber: 20,
    year: 2026,
    startDate: "2026-05-22",
    endDate: "2026-05-29",
  },
  {
    weekNumber: 20,
    year: 2027,
    startDate: "2027-05-21",
    endDate: "2027-05-28",
  },
  {
    weekNumber: 20,
    year: 2028,
    startDate: "2028-05-26",
    endDate: "2028-06-02",
  },
  {
    weekNumber: 20,
    year: 2029,
    startDate: "2029-05-25",
    endDate: "2029-06-01",
  },
  {
    weekNumber: 20,
    year: 2030,
    startDate: "2030-05-24",
    endDate: "2030-05-31",
  },
  {
    weekNumber: 20,
    year: 2031,
    startDate: "2031-05-23",
    endDate: "2031-05-30",
  },
  {
    weekNumber: 20,
    year: 2032,
    startDate: "2032-05-21",
    endDate: "2032-05-28",
  },
  {
    weekNumber: 20,
    year: 2033,
    startDate: "2033-05-27",
    endDate: "2033-06-03",
  },
  {
    weekNumber: 20,
    year: 2034,
    startDate: "2034-05-26",
    endDate: "2034-06-02",
  },
  {
    weekNumber: 20,
    year: 2035,
    startDate: "2035-05-25",
    endDate: "2035-06-01",
  },
  {
    weekNumber: 20,
    year: 2036,
    startDate: "2036-05-23",
    endDate: "2036-05-30",
  },
  {
    weekNumber: 20,
    year: 2037,
    startDate: "2037-05-22",
    endDate: "2037-05-29",
  },
  {
    weekNumber: 20,
    year: 2038,
    startDate: "2038-05-21",
    endDate: "2038-05-28",
  },
  {
    weekNumber: 20,
    year: 2039,
    startDate: "2039-05-27",
    endDate: "2039-06-03",
  },
  {
    weekNumber: 20,
    year: 2040,
    startDate: "2040-05-25",
    endDate: "2040-06-01",
  },
  {
    weekNumber: 21,
    year: 2025,
    startDate: "2025-05-30",
    endDate: "2025-06-06",
  },
  {
    weekNumber: 21,
    year: 2026,
    startDate: "2026-05-29",
    endDate: "2026-06-05",
  },
  {
    weekNumber: 21,
    year: 2027,
    startDate: "2027-05-28",
    endDate: "2027-06-04",
  },
  {
    weekNumber: 21,
    year: 2028,
    startDate: "2028-06-02",
    endDate: "2028-06-09",
  },
  {
    weekNumber: 21,
    year: 2029,
    startDate: "2029-06-01",
    endDate: "2029-06-08",
  },
  {
    weekNumber: 21,
    year: 2030,
    startDate: "2030-05-31",
    endDate: "2030-06-07",
  },
  {
    weekNumber: 21,
    year: 2031,
    startDate: "2031-05-30",
    endDate: "2031-06-06",
  },
  {
    weekNumber: 21,
    year: 2032,
    startDate: "2032-05-28",
    endDate: "2032-06-04",
  },
  {
    weekNumber: 21,
    year: 2033,
    startDate: "2033-06-03",
    endDate: "2033-06-10",
  },
  {
    weekNumber: 21,
    year: 2034,
    startDate: "2034-06-02",
    endDate: "2034-06-09",
  },
  {
    weekNumber: 21,
    year: 2035,
    startDate: "2035-06-01",
    endDate: "2035-06-08",
  },
  {
    weekNumber: 21,
    year: 2036,
    startDate: "2036-05-30",
    endDate: "2036-06-06",
  },
  {
    weekNumber: 21,
    year: 2037,
    startDate: "2037-05-29",
    endDate: "2037-06-05",
  },
  {
    weekNumber: 21,
    year: 2038,
    startDate: "2038-05-28",
    endDate: "2038-06-04",
  },
  {
    weekNumber: 21,
    year: 2039,
    startDate: "2039-06-03",
    endDate: "2039-06-10",
  },
  {
    weekNumber: 21,
    year: 2040,
    startDate: "2040-06-01",
    endDate: "2040-06-08",
  },
  {
    weekNumber: 22,
    year: 2025,
    startDate: "2025-06-06",
    endDate: "2025-06-13",
  },
  {
    weekNumber: 22,
    year: 2026,
    startDate: "2026-06-05",
    endDate: "2026-06-12",
  },
  {
    weekNumber: 22,
    year: 2027,
    startDate: "2027-06-04",
    endDate: "2027-06-11",
  },
  {
    weekNumber: 22,
    year: 2028,
    startDate: "2028-06-09",
    endDate: "2028-06-16",
  },
  {
    weekNumber: 22,
    year: 2029,
    startDate: "2029-06-08",
    endDate: "2029-06-15",
  },
  {
    weekNumber: 22,
    year: 2030,
    startDate: "2030-06-07",
    endDate: "2030-06-14",
  },
  {
    weekNumber: 22,
    year: 2031,
    startDate: "2031-06-06",
    endDate: "2031-06-13",
  },
  {
    weekNumber: 22,
    year: 2032,
    startDate: "2032-06-04",
    endDate: "2032-06-11",
  },
  {
    weekNumber: 22,
    year: 2033,
    startDate: "2033-06-10",
    endDate: "2033-06-17",
  },
  {
    weekNumber: 22,
    year: 2034,
    startDate: "2034-06-09",
    endDate: "2034-06-16",
  },
  {
    weekNumber: 22,
    year: 2035,
    startDate: "2035-06-08",
    endDate: "2035-06-15",
  },
  {
    weekNumber: 22,
    year: 2036,
    startDate: "2036-06-06",
    endDate: "2036-06-13",
  },
  {
    weekNumber: 22,
    year: 2037,
    startDate: "2037-06-05",
    endDate: "2037-06-12",
  },
  {
    weekNumber: 22,
    year: 2038,
    startDate: "2038-06-04",
    endDate: "2038-06-11",
  },
  {
    weekNumber: 22,
    year: 2039,
    startDate: "2039-06-10",
    endDate: "2039-06-17",
  },
  {
    weekNumber: 22,
    year: 2040,
    startDate: "2040-06-08",
    endDate: "2040-06-15",
  },
  {
    weekNumber: 23,
    year: 2025,
    startDate: "2025-06-13",
    endDate: "2025-06-20",
  },
  {
    weekNumber: 23,
    year: 2026,
    startDate: "2026-06-12",
    endDate: "2026-06-19",
  },
  {
    weekNumber: 23,
    year: 2027,
    startDate: "2027-06-11",
    endDate: "2027-06-18",
  },
  {
    weekNumber: 23,
    year: 2028,
    startDate: "2028-06-16",
    endDate: "2028-06-23",
  },
  {
    weekNumber: 23,
    year: 2029,
    startDate: "2029-06-15",
    endDate: "2029-06-22",
  },
  {
    weekNumber: 23,
    year: 2030,
    startDate: "2030-06-14",
    endDate: "2030-06-21",
  },
  {
    weekNumber: 23,
    year: 2031,
    startDate: "2031-06-13",
    endDate: "2031-06-20",
  },
  {
    weekNumber: 23,
    year: 2032,
    startDate: "2032-06-11",
    endDate: "2032-06-18",
  },
  {
    weekNumber: 23,
    year: 2033,
    startDate: "2033-06-17",
    endDate: "2033-06-24",
  },
  {
    weekNumber: 23,
    year: 2034,
    startDate: "2034-06-16",
    endDate: "2034-06-23",
  },
  {
    weekNumber: 23,
    year: 2035,
    startDate: "2035-06-15",
    endDate: "2035-06-22",
  },
  {
    weekNumber: 23,
    year: 2036,
    startDate: "2036-06-13",
    endDate: "2036-06-20",
  },
  {
    weekNumber: 23,
    year: 2037,
    startDate: "2037-06-12",
    endDate: "2037-06-19",
  },
  {
    weekNumber: 23,
    year: 2038,
    startDate: "2038-06-11",
    endDate: "2038-06-18",
  },
  {
    weekNumber: 23,
    year: 2039,
    startDate: "2039-06-17",
    endDate: "2039-06-24",
  },
  {
    weekNumber: 23,
    year: 2040,
    startDate: "2040-06-15",
    endDate: "2040-06-22",
  },
  {
    weekNumber: 24,
    year: 2025,
    startDate: "2025-06-20",
    endDate: "2025-06-27",
  },
  {
    weekNumber: 24,
    year: 2026,
    startDate: "2026-06-19",
    endDate: "2026-06-26",
  },
  {
    weekNumber: 24,
    year: 2027,
    startDate: "2027-06-18",
    endDate: "2027-06-25",
  },
  {
    weekNumber: 24,
    year: 2028,
    startDate: "2028-06-23",
    endDate: "2028-06-30",
  },
  {
    weekNumber: 24,
    year: 2029,
    startDate: "2029-06-22",
    endDate: "2029-06-29",
  },
  {
    weekNumber: 24,
    year: 2030,
    startDate: "2030-06-21",
    endDate: "2030-06-28",
  },
  {
    weekNumber: 24,
    year: 2031,
    startDate: "2031-06-20",
    endDate: "2031-06-27",
  },
  {
    weekNumber: 24,
    year: 2032,
    startDate: "2032-06-18",
    endDate: "2032-06-25",
  },
  {
    weekNumber: 24,
    year: 2033,
    startDate: "2033-06-24",
    endDate: "2033-07-01",
  },
  {
    weekNumber: 24,
    year: 2034,
    startDate: "2034-06-23",
    endDate: "2034-06-30",
  },
  {
    weekNumber: 24,
    year: 2035,
    startDate: "2035-06-22",
    endDate: "2035-06-29",
  },
  {
    weekNumber: 24,
    year: 2036,
    startDate: "2036-06-20",
    endDate: "2036-06-27",
  },
  {
    weekNumber: 24,
    year: 2037,
    startDate: "2037-06-19",
    endDate: "2037-06-26",
  },
  {
    weekNumber: 24,
    year: 2038,
    startDate: "2038-06-18",
    endDate: "2038-06-25",
  },
  {
    weekNumber: 24,
    year: 2039,
    startDate: "2039-06-24",
    endDate: "2039-07-01",
  },
  {
    weekNumber: 24,
    year: 2040,
    startDate: "2040-06-22",
    endDate: "2040-06-29",
  },
  {
    weekNumber: 25,
    year: 2025,
    startDate: "2025-06-27",
    endDate: "2025-07-04",
  },
  {
    weekNumber: 25,
    year: 2026,
    startDate: "2026-06-26",
    endDate: "2026-07-03",
  },
  {
    weekNumber: 25,
    year: 2027,
    startDate: "2027-06-25",
    endDate: "2027-07-02",
  },
  {
    weekNumber: 25,
    year: 2028,
    startDate: "2028-06-30",
    endDate: "2028-07-07",
  },
  {
    weekNumber: 25,
    year: 2029,
    startDate: "2029-06-29",
    endDate: "2029-07-06",
  },
  {
    weekNumber: 25,
    year: 2030,
    startDate: "2030-06-28",
    endDate: "2030-07-05",
  },
  {
    weekNumber: 25,
    year: 2031,
    startDate: "2031-06-27",
    endDate: "2031-07-04",
  },
  {
    weekNumber: 25,
    year: 2032,
    startDate: "2032-06-25",
    endDate: "2032-07-02",
  },
  {
    weekNumber: 25,
    year: 2033,
    startDate: "2033-07-01",
    endDate: "2033-07-08",
  },
  {
    weekNumber: 25,
    year: 2034,
    startDate: "2034-06-30",
    endDate: "2034-07-07",
  },
  {
    weekNumber: 25,
    year: 2035,
    startDate: "2035-06-29",
    endDate: "2035-07-06",
  },
  {
    weekNumber: 25,
    year: 2036,
    startDate: "2036-06-27",
    endDate: "2036-07-04",
  },
  {
    weekNumber: 25,
    year: 2037,
    startDate: "2037-06-26",
    endDate: "2037-07-03",
  },
  {
    weekNumber: 25,
    year: 2038,
    startDate: "2038-06-25",
    endDate: "2038-07-02",
  },
  {
    weekNumber: 25,
    year: 2039,
    startDate: "2039-07-01",
    endDate: "2039-07-08",
  },
  {
    weekNumber: 25,
    year: 2040,
    startDate: "2040-06-29",
    endDate: "2040-07-06",
  },
  {
    weekNumber: 26,
    year: 2025,
    startDate: "2025-07-04",
    endDate: "2025-07-11",
  },
  {
    weekNumber: 26,
    year: 2026,
    startDate: "2026-07-03",
    endDate: "2026-07-10",
  },
  {
    weekNumber: 26,
    year: 2027,
    startDate: "2027-07-02",
    endDate: "2027-07-09",
  },
  {
    weekNumber: 26,
    year: 2028,
    startDate: "2028-07-07",
    endDate: "2028-07-14",
  },
  {
    weekNumber: 26,
    year: 2029,
    startDate: "2029-07-06",
    endDate: "2029-07-13",
  },
  {
    weekNumber: 26,
    year: 2030,
    startDate: "2030-07-05",
    endDate: "2030-07-12",
  },
  {
    weekNumber: 26,
    year: 2031,
    startDate: "2031-07-04",
    endDate: "2031-07-11",
  },
  {
    weekNumber: 26,
    year: 2032,
    startDate: "2032-07-02",
    endDate: "2032-07-09",
  },
  {
    weekNumber: 26,
    year: 2033,
    startDate: "2033-07-08",
    endDate: "2033-07-15",
  },
  {
    weekNumber: 26,
    year: 2034,
    startDate: "2034-07-07",
    endDate: "2034-07-14",
  },
  {
    weekNumber: 26,
    year: 2035,
    startDate: "2035-07-06",
    endDate: "2035-07-13",
  },
  {
    weekNumber: 26,
    year: 2036,
    startDate: "2036-07-04",
    endDate: "2036-07-11",
  },
  {
    weekNumber: 26,
    year: 2037,
    startDate: "2037-07-03",
    endDate: "2037-07-10",
  },
  {
    weekNumber: 26,
    year: 2038,
    startDate: "2038-07-02",
    endDate: "2038-07-09",
  },
  {
    weekNumber: 26,
    year: 2039,
    startDate: "2039-07-08",
    endDate: "2039-07-15",
  },
  {
    weekNumber: 26,
    year: 2040,
    startDate: "2040-07-06",
    endDate: "2040-07-13",
  },
  {
    weekNumber: 27,
    year: 2025,
    startDate: "2025-07-11",
    endDate: "2025-07-18",
  },
  {
    weekNumber: 27,
    year: 2026,
    startDate: "2026-07-10",
    endDate: "2026-07-17",
  },
  {
    weekNumber: 27,
    year: 2027,
    startDate: "2027-07-09",
    endDate: "2027-07-16",
  },
  {
    weekNumber: 27,
    year: 2028,
    startDate: "2028-07-14",
    endDate: "2028-07-21",
  },
  {
    weekNumber: 27,
    year: 2029,
    startDate: "2029-07-13",
    endDate: "2029-07-20",
  },
  {
    weekNumber: 27,
    year: 2030,
    startDate: "2030-07-12",
    endDate: "2030-07-19",
  },
  {
    weekNumber: 27,
    year: 2031,
    startDate: "2031-07-11",
    endDate: "2031-07-18",
  },
  {
    weekNumber: 27,
    year: 2032,
    startDate: "2032-07-09",
    endDate: "2032-07-16",
  },
  {
    weekNumber: 27,
    year: 2033,
    startDate: "2033-07-15",
    endDate: "2033-07-22",
  },
  {
    weekNumber: 27,
    year: 2034,
    startDate: "2034-07-14",
    endDate: "2034-07-21",
  },
  {
    weekNumber: 27,
    year: 2035,
    startDate: "2035-07-13",
    endDate: "2035-07-20",
  },
  {
    weekNumber: 27,
    year: 2036,
    startDate: "2036-07-11",
    endDate: "2036-07-18",
  },
  {
    weekNumber: 27,
    year: 2037,
    startDate: "2037-07-10",
    endDate: "2037-07-17",
  },
  {
    weekNumber: 27,
    year: 2038,
    startDate: "2038-07-09",
    endDate: "2038-07-16",
  },
  {
    weekNumber: 27,
    year: 2039,
    startDate: "2039-07-15",
    endDate: "2039-07-22",
  },
  {
    weekNumber: 27,
    year: 2040,
    startDate: "2040-07-13",
    endDate: "2040-07-20",
  },
  {
    weekNumber: 28,
    year: 2025,
    startDate: "2025-07-18",
    endDate: "2025-07-25",
  },
  {
    weekNumber: 28,
    year: 2026,
    startDate: "2026-07-17",
    endDate: "2026-07-24",
  },
  {
    weekNumber: 28,
    year: 2027,
    startDate: "2027-07-16",
    endDate: "2027-07-23",
  },
  {
    weekNumber: 28,
    year: 2028,
    startDate: "2028-07-21",
    endDate: "2028-07-28",
  },
  {
    weekNumber: 28,
    year: 2029,
    startDate: "2029-07-20",
    endDate: "2029-07-27",
  },
  {
    weekNumber: 28,
    year: 2030,
    startDate: "2030-07-19",
    endDate: "2030-07-26",
  },
  {
    weekNumber: 28,
    year: 2031,
    startDate: "2031-07-18",
    endDate: "2031-07-25",
  },
  {
    weekNumber: 28,
    year: 2032,
    startDate: "2032-07-16",
    endDate: "2032-07-23",
  },
  {
    weekNumber: 28,
    year: 2033,
    startDate: "2033-07-22",
    endDate: "2033-07-29",
  },
  {
    weekNumber: 28,
    year: 2034,
    startDate: "2034-07-21",
    endDate: "2034-07-28",
  },
  {
    weekNumber: 28,
    year: 2035,
    startDate: "2035-07-20",
    endDate: "2035-07-27",
  },
  {
    weekNumber: 28,
    year: 2036,
    startDate: "2036-07-18",
    endDate: "2036-07-25",
  },
  {
    weekNumber: 28,
    year: 2037,
    startDate: "2037-07-17",
    endDate: "2037-07-24",
  },
  {
    weekNumber: 28,
    year: 2038,
    startDate: "2038-07-16",
    endDate: "2038-07-23",
  },
  {
    weekNumber: 28,
    year: 2039,
    startDate: "2039-07-22",
    endDate: "2039-07-29",
  },
  {
    weekNumber: 28,
    year: 2040,
    startDate: "2040-07-20",
    endDate: "2040-07-27",
  },
  {
    weekNumber: 29,
    year: 2025,
    startDate: "2025-07-25",
    endDate: "2025-08-01",
  },
  {
    weekNumber: 29,
    year: 2026,
    startDate: "2026-07-24",
    endDate: "2026-07-31",
  },
  {
    weekNumber: 29,
    year: 2027,
    startDate: "2027-07-23",
    endDate: "2027-07-30",
  },
  {
    weekNumber: 29,
    year: 2028,
    startDate: "2028-07-28",
    endDate: "2028-08-04",
  },
  {
    weekNumber: 29,
    year: 2029,
    startDate: "2029-07-27",
    endDate: "2029-08-03",
  },
  {
    weekNumber: 29,
    year: 2030,
    startDate: "2030-07-26",
    endDate: "2030-08-02",
  },
  {
    weekNumber: 29,
    year: 2031,
    startDate: "2031-07-25",
    endDate: "2031-08-01",
  },
  {
    weekNumber: 29,
    year: 2032,
    startDate: "2032-07-23",
    endDate: "2032-07-30",
  },
  {
    weekNumber: 29,
    year: 2033,
    startDate: "2033-07-29",
    endDate: "2033-08-05",
  },
  {
    weekNumber: 29,
    year: 2034,
    startDate: "2034-07-28",
    endDate: "2034-08-04",
  },
  {
    weekNumber: 29,
    year: 2035,
    startDate: "2035-07-27",
    endDate: "2035-08-03",
  },
  {
    weekNumber: 29,
    year: 2036,
    startDate: "2036-07-25",
    endDate: "2036-08-01",
  },
  {
    weekNumber: 29,
    year: 2037,
    startDate: "2037-07-24",
    endDate: "2037-07-31",
  },
  {
    weekNumber: 29,
    year: 2038,
    startDate: "2038-07-23",
    endDate: "2038-07-30",
  },
  {
    weekNumber: 29,
    year: 2039,
    startDate: "2039-07-29",
    endDate: "2039-08-05",
  },
  {
    weekNumber: 29,
    year: 2040,
    startDate: "2040-07-27",
    endDate: "2040-08-03",
  },
  {
    weekNumber: 30,
    year: 2025,
    startDate: "2025-08-01",
    endDate: "2025-08-08",
  },
  {
    weekNumber: 30,
    year: 2026,
    startDate: "2026-07-31",
    endDate: "2026-08-07",
  },
  {
    weekNumber: 30,
    year: 2027,
    startDate: "2027-07-30",
    endDate: "2027-08-06",
  },
  {
    weekNumber: 30,
    year: 2028,
    startDate: "2028-08-04",
    endDate: "2028-08-11",
  },
  {
    weekNumber: 30,
    year: 2029,
    startDate: "2029-08-03",
    endDate: "2029-08-10",
  },
  {
    weekNumber: 30,
    year: 2030,
    startDate: "2030-08-02",
    endDate: "2030-08-09",
  },
  {
    weekNumber: 30,
    year: 2031,
    startDate: "2031-08-01",
    endDate: "2031-08-08",
  },
  {
    weekNumber: 30,
    year: 2032,
    startDate: "2032-07-30",
    endDate: "2032-08-06",
  },
  {
    weekNumber: 30,
    year: 2033,
    startDate: "2033-08-05",
    endDate: "2033-08-12",
  },
  {
    weekNumber: 30,
    year: 2034,
    startDate: "2034-08-04",
    endDate: "2034-08-11",
  },
  {
    weekNumber: 30,
    year: 2035,
    startDate: "2035-08-03",
    endDate: "2035-08-10",
  },
  {
    weekNumber: 30,
    year: 2036,
    startDate: "2036-08-01",
    endDate: "2036-08-08",
  },
  {
    weekNumber: 30,
    year: 2037,
    startDate: "2037-07-31",
    endDate: "2037-08-07",
  },
  {
    weekNumber: 30,
    year: 2038,
    startDate: "2038-07-30",
    endDate: "2038-08-06",
  },
  {
    weekNumber: 30,
    year: 2039,
    startDate: "2039-08-05",
    endDate: "2039-08-12",
  },
  {
    weekNumber: 30,
    year: 2040,
    startDate: "2040-08-03",
    endDate: "2040-08-10",
  },
  {
    weekNumber: 31,
    year: 2025,
    startDate: "2025-08-08",
    endDate: "2025-08-15",
  },
  {
    weekNumber: 31,
    year: 2026,
    startDate: "2026-08-07",
    endDate: "2026-08-14",
  },
  {
    weekNumber: 31,
    year: 2027,
    startDate: "2027-08-06",
    endDate: "2027-08-13",
  },
  {
    weekNumber: 31,
    year: 2028,
    startDate: "2028-08-11",
    endDate: "2028-08-18",
  },
  {
    weekNumber: 31,
    year: 2029,
    startDate: "2029-08-10",
    endDate: "2029-08-17",
  },
  {
    weekNumber: 31,
    year: 2030,
    startDate: "2030-08-09",
    endDate: "2030-08-16",
  },
  {
    weekNumber: 31,
    year: 2031,
    startDate: "2031-08-08",
    endDate: "2031-08-15",
  },
  {
    weekNumber: 31,
    year: 2032,
    startDate: "2032-08-06",
    endDate: "2032-08-13",
  },
  {
    weekNumber: 31,
    year: 2033,
    startDate: "2033-08-12",
    endDate: "2033-08-19",
  },
  {
    weekNumber: 31,
    year: 2034,
    startDate: "2034-08-11",
    endDate: "2034-08-18",
  },
  {
    weekNumber: 31,
    year: 2035,
    startDate: "2035-08-10",
    endDate: "2035-08-17",
  },
  {
    weekNumber: 31,
    year: 2036,
    startDate: "2036-08-08",
    endDate: "2036-08-15",
  },
  {
    weekNumber: 31,
    year: 2037,
    startDate: "2037-08-07",
    endDate: "2037-08-14",
  },
  {
    weekNumber: 31,
    year: 2038,
    startDate: "2038-08-06",
    endDate: "2038-08-13",
  },
  {
    weekNumber: 31,
    year: 2039,
    startDate: "2039-08-12",
    endDate: "2039-08-19",
  },
  {
    weekNumber: 31,
    year: 2040,
    startDate: "2040-08-10",
    endDate: "2040-08-17",
  },
  {
    weekNumber: 32,
    year: 2025,
    startDate: "2025-08-15",
    endDate: "2025-08-22",
  },
  {
    weekNumber: 32,
    year: 2026,
    startDate: "2026-08-14",
    endDate: "2026-08-21",
  },
  {
    weekNumber: 32,
    year: 2027,
    startDate: "2027-08-13",
    endDate: "2027-08-20",
  },
  {
    weekNumber: 32,
    year: 2028,
    startDate: "2028-08-18",
    endDate: "2028-08-25",
  },
  {
    weekNumber: 32,
    year: 2029,
    startDate: "2029-08-17",
    endDate: "2029-08-24",
  },
  {
    weekNumber: 32,
    year: 2030,
    startDate: "2030-08-16",
    endDate: "2030-08-23",
  },
  {
    weekNumber: 32,
    year: 2031,
    startDate: "2031-08-15",
    endDate: "2031-08-22",
  },
  {
    weekNumber: 32,
    year: 2032,
    startDate: "2032-08-13",
    endDate: "2032-08-20",
  },
  {
    weekNumber: 32,
    year: 2033,
    startDate: "2033-08-19",
    endDate: "2033-08-26",
  },
  {
    weekNumber: 32,
    year: 2034,
    startDate: "2034-08-18",
    endDate: "2034-08-25",
  },
  {
    weekNumber: 32,
    year: 2035,
    startDate: "2035-08-17",
    endDate: "2035-08-24",
  },
  {
    weekNumber: 32,
    year: 2036,
    startDate: "2036-08-15",
    endDate: "2036-08-22",
  },
  {
    weekNumber: 32,
    year: 2037,
    startDate: "2037-08-14",
    endDate: "2037-08-21",
  },
  {
    weekNumber: 32,
    year: 2038,
    startDate: "2038-08-13",
    endDate: "2038-08-20",
  },
  {
    weekNumber: 32,
    year: 2039,
    startDate: "2039-08-19",
    endDate: "2039-08-26",
  },
  {
    weekNumber: 32,
    year: 2040,
    startDate: "2040-08-17",
    endDate: "2040-08-24",
  },
  {
    weekNumber: 33,
    year: 2025,
    startDate: "2025-08-22",
    endDate: "2025-08-29",
  },
  {
    weekNumber: 33,
    year: 2026,
    startDate: "2026-08-21",
    endDate: "2026-08-28",
  },
  {
    weekNumber: 33,
    year: 2027,
    startDate: "2027-08-20",
    endDate: "2027-08-27",
  },
  {
    weekNumber: 33,
    year: 2028,
    startDate: "2028-08-25",
    endDate: "2028-09-01",
  },
  {
    weekNumber: 33,
    year: 2029,
    startDate: "2029-08-24",
    endDate: "2029-08-31",
  },
  {
    weekNumber: 33,
    year: 2030,
    startDate: "2030-08-23",
    endDate: "2030-08-30",
  },
  {
    weekNumber: 33,
    year: 2031,
    startDate: "2031-08-22",
    endDate: "2031-08-29",
  },
  {
    weekNumber: 33,
    year: 2032,
    startDate: "2032-08-20",
    endDate: "2032-08-27",
  },
  {
    weekNumber: 33,
    year: 2033,
    startDate: "2033-08-26",
    endDate: "2033-09-02",
  },
  {
    weekNumber: 33,
    year: 2034,
    startDate: "2034-08-25",
    endDate: "2034-09-01",
  },
  {
    weekNumber: 33,
    year: 2035,
    startDate: "2035-08-24",
    endDate: "2035-08-31",
  },
  {
    weekNumber: 33,
    year: 2036,
    startDate: "2036-08-22",
    endDate: "2036-08-29",
  },
  {
    weekNumber: 33,
    year: 2037,
    startDate: "2037-08-21",
    endDate: "2037-08-28",
  },
  {
    weekNumber: 33,
    year: 2038,
    startDate: "2038-08-20",
    endDate: "2038-08-27",
  },
  {
    weekNumber: 33,
    year: 2039,
    startDate: "2039-08-26",
    endDate: "2039-09-02",
  },
  {
    weekNumber: 33,
    year: 2040,
    startDate: "2040-08-24",
    endDate: "2040-08-31",
  },
  {
    weekNumber: 34,
    year: 2025,
    startDate: "2025-08-29",
    endDate: "2025-09-05",
  },
  {
    weekNumber: 34,
    year: 2026,
    startDate: "2026-08-28",
    endDate: "2026-09-04",
  },
  {
    weekNumber: 34,
    year: 2027,
    startDate: "2027-08-27",
    endDate: "2027-09-03",
  },
  {
    weekNumber: 34,
    year: 2028,
    startDate: "2028-09-01",
    endDate: "2028-09-08",
  },
  {
    weekNumber: 34,
    year: 2029,
    startDate: "2029-08-31",
    endDate: "2029-09-07",
  },
  {
    weekNumber: 34,
    year: 2030,
    startDate: "2030-08-30",
    endDate: "2030-09-06",
  },
  {
    weekNumber: 34,
    year: 2031,
    startDate: "2031-08-29",
    endDate: "2031-09-05",
  },
  {
    weekNumber: 34,
    year: 2032,
    startDate: "2032-08-27",
    endDate: "2032-09-03",
  },
  {
    weekNumber: 34,
    year: 2033,
    startDate: "2033-09-02",
    endDate: "2033-09-09",
  },
  {
    weekNumber: 34,
    year: 2034,
    startDate: "2034-09-01",
    endDate: "2034-09-08",
  },
  {
    weekNumber: 34,
    year: 2035,
    startDate: "2035-08-31",
    endDate: "2035-09-07",
  },
  {
    weekNumber: 34,
    year: 2036,
    startDate: "2036-08-29",
    endDate: "2036-09-05",
  },
  {
    weekNumber: 34,
    year: 2037,
    startDate: "2037-08-28",
    endDate: "2037-09-04",
  },
  {
    weekNumber: 34,
    year: 2038,
    startDate: "2038-08-27",
    endDate: "2038-09-03",
  },
  {
    weekNumber: 34,
    year: 2039,
    startDate: "2039-09-02",
    endDate: "2039-09-09",
  },
  {
    weekNumber: 34,
    year: 2040,
    startDate: "2040-08-31",
    endDate: "2040-09-07",
  },
  {
    weekNumber: 35,
    year: 2025,
    startDate: "2025-09-05",
    endDate: "2025-09-12",
  },
  {
    weekNumber: 35,
    year: 2026,
    startDate: "2026-09-04",
    endDate: "2026-09-11",
  },
  {
    weekNumber: 35,
    year: 2027,
    startDate: "2027-09-03",
    endDate: "2027-09-10",
  },
  {
    weekNumber: 35,
    year: 2028,
    startDate: "2028-09-08",
    endDate: "2028-09-15",
  },
  {
    weekNumber: 35,
    year: 2029,
    startDate: "2029-09-07",
    endDate: "2029-09-14",
  },
  {
    weekNumber: 35,
    year: 2030,
    startDate: "2030-09-06",
    endDate: "2030-09-13",
  },
  {
    weekNumber: 35,
    year: 2031,
    startDate: "2031-09-05",
    endDate: "2031-09-12",
  },
  {
    weekNumber: 35,
    year: 2032,
    startDate: "2032-09-03",
    endDate: "2032-09-10",
  },
  {
    weekNumber: 35,
    year: 2033,
    startDate: "2033-09-09",
    endDate: "2033-09-16",
  },
  {
    weekNumber: 35,
    year: 2034,
    startDate: "2034-09-08",
    endDate: "2034-09-15",
  },
  {
    weekNumber: 35,
    year: 2035,
    startDate: "2035-09-07",
    endDate: "2035-09-14",
  },
  {
    weekNumber: 35,
    year: 2036,
    startDate: "2036-09-05",
    endDate: "2036-09-12",
  },
  {
    weekNumber: 35,
    year: 2037,
    startDate: "2037-09-04",
    endDate: "2037-09-11",
  },
  {
    weekNumber: 35,
    year: 2038,
    startDate: "2038-09-03",
    endDate: "2038-09-10",
  },
  {
    weekNumber: 35,
    year: 2039,
    startDate: "2039-09-09",
    endDate: "2039-09-16",
  },
  {
    weekNumber: 35,
    year: 2040,
    startDate: "2040-09-07",
    endDate: "2040-09-14",
  },
  {
    weekNumber: 36,
    year: 2025,
    startDate: "2025-09-12",
    endDate: "2025-09-19",
  },
  {
    weekNumber: 36,
    year: 2026,
    startDate: "2026-09-11",
    endDate: "2026-09-18",
  },
  {
    weekNumber: 36,
    year: 2027,
    startDate: "2027-09-10",
    endDate: "2027-09-17",
  },
  {
    weekNumber: 36,
    year: 2028,
    startDate: "2028-09-15",
    endDate: "2028-09-22",
  },
  {
    weekNumber: 36,
    year: 2029,
    startDate: "2029-09-14",
    endDate: "2029-09-21",
  },
  {
    weekNumber: 36,
    year: 2030,
    startDate: "2030-09-13",
    endDate: "2030-09-20",
  },
  {
    weekNumber: 36,
    year: 2031,
    startDate: "2031-09-12",
    endDate: "2031-09-19",
  },
  {
    weekNumber: 36,
    year: 2032,
    startDate: "2032-09-10",
    endDate: "2032-09-17",
  },
  {
    weekNumber: 36,
    year: 2033,
    startDate: "2033-09-16",
    endDate: "2033-09-23",
  },
  {
    weekNumber: 36,
    year: 2034,
    startDate: "2034-09-15",
    endDate: "2034-09-22",
  },
  {
    weekNumber: 36,
    year: 2035,
    startDate: "2035-09-14",
    endDate: "2035-09-21",
  },
  {
    weekNumber: 36,
    year: 2036,
    startDate: "2036-09-12",
    endDate: "2036-09-19",
  },
  {
    weekNumber: 36,
    year: 2037,
    startDate: "2037-09-11",
    endDate: "2037-09-18",
  },
  {
    weekNumber: 36,
    year: 2038,
    startDate: "2038-09-10",
    endDate: "2038-09-17",
  },
  {
    weekNumber: 36,
    year: 2039,
    startDate: "2039-09-16",
    endDate: "2039-09-23",
  },
  {
    weekNumber: 36,
    year: 2040,
    startDate: "2040-09-14",
    endDate: "2040-09-21",
  },
  {
    weekNumber: 37,
    year: 2025,
    startDate: "2025-09-19",
    endDate: "2025-09-26",
  },
  {
    weekNumber: 37,
    year: 2026,
    startDate: "2026-09-18",
    endDate: "2026-09-25",
  },
  {
    weekNumber: 37,
    year: 2027,
    startDate: "2027-09-17",
    endDate: "2027-09-24",
  },
  {
    weekNumber: 37,
    year: 2028,
    startDate: "2028-09-22",
    endDate: "2028-09-29",
  },
  {
    weekNumber: 37,
    year: 2029,
    startDate: "2029-09-21",
    endDate: "2029-09-28",
  },
  {
    weekNumber: 37,
    year: 2030,
    startDate: "2030-09-20",
    endDate: "2030-09-27",
  },
  {
    weekNumber: 37,
    year: 2031,
    startDate: "2031-09-19",
    endDate: "2031-09-26",
  },
  {
    weekNumber: 37,
    year: 2032,
    startDate: "2032-09-17",
    endDate: "2032-09-24",
  },
  {
    weekNumber: 37,
    year: 2033,
    startDate: "2033-09-23",
    endDate: "2033-09-30",
  },
  {
    weekNumber: 37,
    year: 2034,
    startDate: "2034-09-22",
    endDate: "2034-09-29",
  },
  {
    weekNumber: 37,
    year: 2035,
    startDate: "2035-09-21",
    endDate: "2035-09-28",
  },
  {
    weekNumber: 37,
    year: 2036,
    startDate: "2036-09-19",
    endDate: "2036-09-26",
  },
  {
    weekNumber: 37,
    year: 2037,
    startDate: "2037-09-18",
    endDate: "2037-09-25",
  },
  {
    weekNumber: 37,
    year: 2038,
    startDate: "2038-09-17",
    endDate: "2038-09-24",
  },
  {
    weekNumber: 37,
    year: 2039,
    startDate: "2039-09-23",
    endDate: "2039-09-30",
  },
  {
    weekNumber: 37,
    year: 2040,
    startDate: "2040-09-21",
    endDate: "2040-09-28",
  },
  {
    weekNumber: 38,
    year: 2025,
    startDate: "2025-09-26",
    endDate: "2025-10-03",
  },
  {
    weekNumber: 38,
    year: 2026,
    startDate: "2026-09-25",
    endDate: "2026-10-02",
  },
  {
    weekNumber: 38,
    year: 2027,
    startDate: "2027-09-24",
    endDate: "2027-10-01",
  },
  {
    weekNumber: 38,
    year: 2028,
    startDate: "2028-09-29",
    endDate: "2028-10-06",
  },
  {
    weekNumber: 38,
    year: 2029,
    startDate: "2029-09-28",
    endDate: "2029-10-05",
  },
  {
    weekNumber: 38,
    year: 2030,
    startDate: "2030-09-27",
    endDate: "2030-10-04",
  },
  {
    weekNumber: 38,
    year: 2031,
    startDate: "2031-09-26",
    endDate: "2031-10-03",
  },
  {
    weekNumber: 38,
    year: 2032,
    startDate: "2032-09-24",
    endDate: "2032-10-01",
  },
  {
    weekNumber: 38,
    year: 2033,
    startDate: "2033-09-30",
    endDate: "2033-10-07",
  },
  {
    weekNumber: 38,
    year: 2034,
    startDate: "2034-09-29",
    endDate: "2034-10-06",
  },
  {
    weekNumber: 38,
    year: 2035,
    startDate: "2035-09-28",
    endDate: "2035-10-05",
  },
  {
    weekNumber: 38,
    year: 2036,
    startDate: "2036-09-26",
    endDate: "2036-10-03",
  },
  {
    weekNumber: 38,
    year: 2037,
    startDate: "2037-09-25",
    endDate: "2037-10-02",
  },
  {
    weekNumber: 38,
    year: 2038,
    startDate: "2038-09-24",
    endDate: "2038-10-01",
  },
  {
    weekNumber: 38,
    year: 2039,
    startDate: "2039-09-30",
    endDate: "2039-10-07",
  },
  {
    weekNumber: 38,
    year: 2040,
    startDate: "2040-09-28",
    endDate: "2040-10-05",
  },
  {
    weekNumber: 39,
    year: 2025,
    startDate: "2025-10-03",
    endDate: "2025-10-10",
  },
  {
    weekNumber: 39,
    year: 2026,
    startDate: "2026-10-02",
    endDate: "2026-10-09",
  },
  {
    weekNumber: 39,
    year: 2027,
    startDate: "2027-10-01",
    endDate: "2027-10-08",
  },
  {
    weekNumber: 39,
    year: 2028,
    startDate: "2028-10-06",
    endDate: "2028-10-13",
  },
  {
    weekNumber: 39,
    year: 2029,
    startDate: "2029-10-05",
    endDate: "2029-10-12",
  },
  {
    weekNumber: 39,
    year: 2030,
    startDate: "2030-10-04",
    endDate: "2030-10-11",
  },
  {
    weekNumber: 39,
    year: 2031,
    startDate: "2031-10-03",
    endDate: "2031-10-10",
  },
  {
    weekNumber: 39,
    year: 2032,
    startDate: "2032-10-01",
    endDate: "2032-10-08",
  },
  {
    weekNumber: 39,
    year: 2033,
    startDate: "2033-10-07",
    endDate: "2033-10-14",
  },
  {
    weekNumber: 39,
    year: 2034,
    startDate: "2034-10-06",
    endDate: "2034-10-13",
  },
  {
    weekNumber: 39,
    year: 2035,
    startDate: "2035-10-05",
    endDate: "2035-10-12",
  },
  {
    weekNumber: 39,
    year: 2036,
    startDate: "2036-10-03",
    endDate: "2036-10-10",
  },
  {
    weekNumber: 39,
    year: 2037,
    startDate: "2037-10-02",
    endDate: "2037-10-09",
  },
  {
    weekNumber: 39,
    year: 2038,
    startDate: "2038-10-01",
    endDate: "2038-10-08",
  },
  {
    weekNumber: 39,
    year: 2039,
    startDate: "2039-10-07",
    endDate: "2039-10-14",
  },
  {
    weekNumber: 39,
    year: 2040,
    startDate: "2040-10-05",
    endDate: "2040-10-12",
  },
  {
    weekNumber: 40,
    year: 2025,
    startDate: "2025-10-10",
    endDate: "2025-10-17",
  },
  {
    weekNumber: 40,
    year: 2026,
    startDate: "2026-10-09",
    endDate: "2026-10-16",
  },
  {
    weekNumber: 40,
    year: 2027,
    startDate: "2027-10-08",
    endDate: "2027-10-15",
  },
  {
    weekNumber: 40,
    year: 2028,
    startDate: "2028-10-13",
    endDate: "2028-10-20",
  },
  {
    weekNumber: 40,
    year: 2029,
    startDate: "2029-10-12",
    endDate: "2029-10-19",
  },
  {
    weekNumber: 40,
    year: 2030,
    startDate: "2030-10-11",
    endDate: "2030-10-18",
  },
  {
    weekNumber: 40,
    year: 2031,
    startDate: "2031-10-10",
    endDate: "2031-10-17",
  },
  {
    weekNumber: 40,
    year: 2032,
    startDate: "2032-10-08",
    endDate: "2032-10-15",
  },
  {
    weekNumber: 40,
    year: 2033,
    startDate: "2033-10-14",
    endDate: "2033-10-21",
  },
  {
    weekNumber: 40,
    year: 2034,
    startDate: "2034-10-13",
    endDate: "2034-10-20",
  },
  {
    weekNumber: 40,
    year: 2035,
    startDate: "2035-10-12",
    endDate: "2035-10-19",
  },
  {
    weekNumber: 40,
    year: 2036,
    startDate: "2036-10-10",
    endDate: "2036-10-17",
  },
  {
    weekNumber: 40,
    year: 2037,
    startDate: "2037-10-09",
    endDate: "2037-10-16",
  },
  {
    weekNumber: 40,
    year: 2038,
    startDate: "2038-10-08",
    endDate: "2038-10-15",
  },
  {
    weekNumber: 40,
    year: 2039,
    startDate: "2039-10-14",
    endDate: "2039-10-21",
  },
  {
    weekNumber: 40,
    year: 2040,
    startDate: "2040-10-12",
    endDate: "2040-10-19",
  },
  {
    weekNumber: 41,
    year: 2025,
    startDate: "2025-10-17",
    endDate: "2025-10-24",
  },
  {
    weekNumber: 41,
    year: 2026,
    startDate: "2026-10-16",
    endDate: "2026-10-23",
  },
  {
    weekNumber: 41,
    year: 2027,
    startDate: "2027-10-15",
    endDate: "2027-10-22",
  },
  {
    weekNumber: 41,
    year: 2028,
    startDate: "2028-10-20",
    endDate: "2028-10-27",
  },
  {
    weekNumber: 41,
    year: 2029,
    startDate: "2029-10-19",
    endDate: "2029-10-26",
  },
  {
    weekNumber: 41,
    year: 2030,
    startDate: "2030-10-18",
    endDate: "2030-10-25",
  },
  {
    weekNumber: 41,
    year: 2031,
    startDate: "2031-10-17",
    endDate: "2031-10-24",
  },
  {
    weekNumber: 41,
    year: 2032,
    startDate: "2032-10-15",
    endDate: "2032-10-22",
  },
  {
    weekNumber: 41,
    year: 2033,
    startDate: "2033-10-21",
    endDate: "2033-10-28",
  },
  {
    weekNumber: 41,
    year: 2034,
    startDate: "2034-10-20",
    endDate: "2034-10-27",
  },
  {
    weekNumber: 41,
    year: 2035,
    startDate: "2035-10-19",
    endDate: "2035-10-26",
  },
  {
    weekNumber: 41,
    year: 2036,
    startDate: "2036-10-17",
    endDate: "2036-10-24",
  },
  {
    weekNumber: 41,
    year: 2037,
    startDate: "2037-10-16",
    endDate: "2037-10-23",
  },
  {
    weekNumber: 41,
    year: 2038,
    startDate: "2038-10-15",
    endDate: "2038-10-22",
  },
  {
    weekNumber: 41,
    year: 2039,
    startDate: "2039-10-21",
    endDate: "2039-10-28",
  },
  {
    weekNumber: 41,
    year: 2040,
    startDate: "2040-10-19",
    endDate: "2040-10-26",
  },
  {
    weekNumber: 42,
    year: 2025,
    startDate: "2025-10-24",
    endDate: "2025-10-31",
  },
  {
    weekNumber: 42,
    year: 2026,
    startDate: "2026-10-23",
    endDate: "2026-10-30",
  },
  {
    weekNumber: 42,
    year: 2027,
    startDate: "2027-10-22",
    endDate: "2027-10-29",
  },
  {
    weekNumber: 42,
    year: 2028,
    startDate: "2028-10-27",
    endDate: "2028-11-03",
  },
  {
    weekNumber: 42,
    year: 2029,
    startDate: "2029-10-26",
    endDate: "2029-11-02",
  },
  {
    weekNumber: 42,
    year: 2030,
    startDate: "2030-10-25",
    endDate: "2030-11-01",
  },
  {
    weekNumber: 42,
    year: 2031,
    startDate: "2031-10-24",
    endDate: "2031-10-31",
  },
  {
    weekNumber: 42,
    year: 2032,
    startDate: "2032-10-22",
    endDate: "2032-10-29",
  },
  {
    weekNumber: 42,
    year: 2033,
    startDate: "2033-10-28",
    endDate: "2033-11-04",
  },
  {
    weekNumber: 42,
    year: 2034,
    startDate: "2034-10-27",
    endDate: "2034-11-03",
  },
  {
    weekNumber: 42,
    year: 2035,
    startDate: "2035-10-26",
    endDate: "2035-11-02",
  },
  {
    weekNumber: 42,
    year: 2036,
    startDate: "2036-10-24",
    endDate: "2036-10-31",
  },
  {
    weekNumber: 42,
    year: 2037,
    startDate: "2037-10-23",
    endDate: "2037-10-30",
  },
  {
    weekNumber: 42,
    year: 2038,
    startDate: "2038-10-22",
    endDate: "2038-10-29",
  },
  {
    weekNumber: 42,
    year: 2039,
    startDate: "2039-10-28",
    endDate: "2039-11-04",
  },
  {
    weekNumber: 42,
    year: 2040,
    startDate: "2040-10-26",
    endDate: "2040-11-02",
  },
  {
    weekNumber: 43,
    year: 2025,
    startDate: "2025-10-31",
    endDate: "2025-11-07",
  },
  {
    weekNumber: 43,
    year: 2026,
    startDate: "2026-10-30",
    endDate: "2026-11-06",
  },
  {
    weekNumber: 43,
    year: 2027,
    startDate: "2027-10-29",
    endDate: "2027-11-05",
  },
  {
    weekNumber: 43,
    year: 2028,
    startDate: "2028-11-03",
    endDate: "2028-11-10",
  },
  {
    weekNumber: 43,
    year: 2029,
    startDate: "2029-11-02",
    endDate: "2029-11-09",
  },
  {
    weekNumber: 43,
    year: 2030,
    startDate: "2030-11-01",
    endDate: "2030-11-08",
  },
  {
    weekNumber: 43,
    year: 2031,
    startDate: "2031-10-31",
    endDate: "2031-11-07",
  },
  {
    weekNumber: 43,
    year: 2032,
    startDate: "2032-10-29",
    endDate: "2032-11-05",
  },
  {
    weekNumber: 43,
    year: 2033,
    startDate: "2033-11-04",
    endDate: "2033-11-11",
  },
  {
    weekNumber: 43,
    year: 2034,
    startDate: "2034-11-03",
    endDate: "2034-11-10",
  },
  {
    weekNumber: 43,
    year: 2035,
    startDate: "2035-11-02",
    endDate: "2035-11-09",
  },
  {
    weekNumber: 43,
    year: 2036,
    startDate: "2036-10-31",
    endDate: "2036-11-07",
  },
  {
    weekNumber: 43,
    year: 2037,
    startDate: "2037-10-30",
    endDate: "2037-11-06",
  },
  {
    weekNumber: 43,
    year: 2038,
    startDate: "2038-10-29",
    endDate: "2038-11-05",
  },
  {
    weekNumber: 43,
    year: 2039,
    startDate: "2039-11-04",
    endDate: "2039-11-11",
  },
  {
    weekNumber: 43,
    year: 2040,
    startDate: "2040-11-02",
    endDate: "2040-11-09",
  },
  {
    weekNumber: 44,
    year: 2025,
    startDate: "2025-11-07",
    endDate: "2025-11-14",
  },
  {
    weekNumber: 44,
    year: 2026,
    startDate: "2026-11-06",
    endDate: "2026-11-13",
  },
  {
    weekNumber: 44,
    year: 2027,
    startDate: "2027-11-05",
    endDate: "2027-11-12",
  },
  {
    weekNumber: 44,
    year: 2028,
    startDate: "2028-11-10",
    endDate: "2028-11-17",
  },
  {
    weekNumber: 44,
    year: 2029,
    startDate: "2029-11-09",
    endDate: "2029-11-16",
  },
  {
    weekNumber: 44,
    year: 2030,
    startDate: "2030-11-08",
    endDate: "2030-11-15",
  },
  {
    weekNumber: 44,
    year: 2031,
    startDate: "2031-11-07",
    endDate: "2031-11-14",
  },
  {
    weekNumber: 44,
    year: 2032,
    startDate: "2032-11-05",
    endDate: "2032-11-12",
  },
  {
    weekNumber: 44,
    year: 2033,
    startDate: "2033-11-11",
    endDate: "2033-11-18",
  },
  {
    weekNumber: 44,
    year: 2034,
    startDate: "2034-11-10",
    endDate: "2034-11-17",
  },
  {
    weekNumber: 44,
    year: 2035,
    startDate: "2035-11-09",
    endDate: "2035-11-16",
  },
  {
    weekNumber: 44,
    year: 2036,
    startDate: "2036-11-07",
    endDate: "2036-11-14",
  },
  {
    weekNumber: 44,
    year: 2037,
    startDate: "2037-11-06",
    endDate: "2037-11-13",
  },
  {
    weekNumber: 44,
    year: 2038,
    startDate: "2038-11-05",
    endDate: "2038-11-12",
  },
  {
    weekNumber: 44,
    year: 2039,
    startDate: "2039-11-11",
    endDate: "2039-11-18",
  },
  {
    weekNumber: 44,
    year: 2040,
    startDate: "2040-11-09",
    endDate: "2040-11-16",
  },
  {
    weekNumber: 45,
    year: 2025,
    startDate: "2025-11-14",
    endDate: "2025-11-21",
  },
  {
    weekNumber: 45,
    year: 2026,
    startDate: "2026-11-13",
    endDate: "2026-11-20",
  },
  {
    weekNumber: 45,
    year: 2027,
    startDate: "2027-11-12",
    endDate: "2027-11-19",
  },
  {
    weekNumber: 45,
    year: 2028,
    startDate: "2028-11-17",
    endDate: "2028-11-24",
  },
  {
    weekNumber: 45,
    year: 2029,
    startDate: "2029-11-16",
    endDate: "2029-11-23",
  },
  {
    weekNumber: 45,
    year: 2030,
    startDate: "2030-11-15",
    endDate: "2030-11-22",
  },
  {
    weekNumber: 45,
    year: 2031,
    startDate: "2031-11-14",
    endDate: "2031-11-21",
  },
  {
    weekNumber: 45,
    year: 2032,
    startDate: "2032-11-12",
    endDate: "2032-11-19",
  },
  {
    weekNumber: 45,
    year: 2033,
    startDate: "2033-11-18",
    endDate: "2033-11-25",
  },
  {
    weekNumber: 45,
    year: 2034,
    startDate: "2034-11-17",
    endDate: "2034-11-24",
  },
  {
    weekNumber: 45,
    year: 2035,
    startDate: "2035-11-16",
    endDate: "2035-11-23",
  },
  {
    weekNumber: 45,
    year: 2036,
    startDate: "2036-11-14",
    endDate: "2036-11-21",
  },
  {
    weekNumber: 45,
    year: 2037,
    startDate: "2037-11-13",
    endDate: "2037-11-20",
  },
  {
    weekNumber: 45,
    year: 2038,
    startDate: "2038-11-12",
    endDate: "2038-11-19",
  },
  {
    weekNumber: 45,
    year: 2039,
    startDate: "2039-11-18",
    endDate: "2039-11-25",
  },
  {
    weekNumber: 45,
    year: 2040,
    startDate: "2040-11-16",
    endDate: "2040-11-23",
  },
  {
    weekNumber: 46,
    year: 2025,
    startDate: "2025-11-21",
    endDate: "2025-11-28",
  },
  {
    weekNumber: 46,
    year: 2026,
    startDate: "2026-11-20",
    endDate: "2026-11-27",
  },
  {
    weekNumber: 46,
    year: 2027,
    startDate: "2027-11-19",
    endDate: "2027-11-26",
  },
  {
    weekNumber: 46,
    year: 2028,
    startDate: "2028-11-24",
    endDate: "2028-12-01",
  },
  {
    weekNumber: 46,
    year: 2029,
    startDate: "2029-11-23",
    endDate: "2029-11-30",
  },
  {
    weekNumber: 46,
    year: 2030,
    startDate: "2030-11-22",
    endDate: "2030-11-29",
  },
  {
    weekNumber: 46,
    year: 2031,
    startDate: "2031-11-21",
    endDate: "2031-11-28",
  },
  {
    weekNumber: 46,
    year: 2032,
    startDate: "2032-11-19",
    endDate: "2032-11-26",
  },
  {
    weekNumber: 46,
    year: 2033,
    startDate: "2033-11-25",
    endDate: "2033-12-02",
  },
  {
    weekNumber: 46,
    year: 2034,
    startDate: "2034-11-24",
    endDate: "2034-12-01",
  },
  {
    weekNumber: 46,
    year: 2035,
    startDate: "2035-11-23",
    endDate: "2035-11-30",
  },
  {
    weekNumber: 46,
    year: 2036,
    startDate: "2036-11-21",
    endDate: "2036-11-28",
  },
  {
    weekNumber: 46,
    year: 2037,
    startDate: "2037-11-20",
    endDate: "2037-11-27",
  },
  {
    weekNumber: 46,
    year: 2038,
    startDate: "2038-11-19",
    endDate: "2038-11-26",
  },
  {
    weekNumber: 46,
    year: 2039,
    startDate: "2039-11-25",
    endDate: "2039-12-02",
  },
  {
    weekNumber: 46,
    year: 2040,
    startDate: "2040-11-23",
    endDate: "2040-11-30",
  },
  {
    weekNumber: 47,
    year: 2025,
    startDate: "2025-11-28",
    endDate: "2025-12-05",
  },
  {
    weekNumber: 47,
    year: 2026,
    startDate: "2026-11-27",
    endDate: "2026-12-04",
  },
  {
    weekNumber: 47,
    year: 2027,
    startDate: "2027-11-26",
    endDate: "2027-12-03",
  },
  {
    weekNumber: 47,
    year: 2028,
    startDate: "2028-12-01",
    endDate: "2028-12-08",
  },
  {
    weekNumber: 47,
    year: 2029,
    startDate: "2029-11-30",
    endDate: "2029-12-07",
  },
  {
    weekNumber: 47,
    year: 2030,
    startDate: "2030-11-29",
    endDate: "2030-12-06",
  },
  {
    weekNumber: 47,
    year: 2031,
    startDate: "2031-11-28",
    endDate: "2031-12-05",
  },
  {
    weekNumber: 47,
    year: 2032,
    startDate: "2032-11-26",
    endDate: "2032-12-03",
  },
  {
    weekNumber: 47,
    year: 2033,
    startDate: "2033-12-02",
    endDate: "2033-12-09",
  },
  {
    weekNumber: 47,
    year: 2034,
    startDate: "2034-12-01",
    endDate: "2034-12-08",
  },
  {
    weekNumber: 47,
    year: 2035,
    startDate: "2035-11-30",
    endDate: "2035-12-07",
  },
  {
    weekNumber: 47,
    year: 2036,
    startDate: "2036-11-28",
    endDate: "2036-12-05",
  },
  {
    weekNumber: 47,
    year: 2037,
    startDate: "2037-11-27",
    endDate: "2037-12-04",
  },
  {
    weekNumber: 47,
    year: 2038,
    startDate: "2038-11-26",
    endDate: "2038-12-03",
  },
  {
    weekNumber: 47,
    year: 2039,
    startDate: "2039-12-02",
    endDate: "2039-12-09",
  },
  {
    weekNumber: 47,
    year: 2040,
    startDate: "2040-11-30",
    endDate: "2040-12-07",
  },
  {
    weekNumber: 48,
    year: 2025,
    startDate: "2025-12-05",
    endDate: "2025-12-12",
  },
  {
    weekNumber: 48,
    year: 2026,
    startDate: "2026-12-04",
    endDate: "2026-12-11",
  },
  {
    weekNumber: 48,
    year: 2027,
    startDate: "2027-12-03",
    endDate: "2027-12-10",
  },
  {
    weekNumber: 48,
    year: 2028,
    startDate: "2028-12-08",
    endDate: "2028-12-15",
  },
  {
    weekNumber: 48,
    year: 2029,
    startDate: "2029-12-07",
    endDate: "2029-12-14",
  },
  {
    weekNumber: 48,
    year: 2030,
    startDate: "2030-12-06",
    endDate: "2030-12-13",
  },
  {
    weekNumber: 48,
    year: 2031,
    startDate: "2031-12-05",
    endDate: "2031-12-12",
  },
  {
    weekNumber: 48,
    year: 2032,
    startDate: "2032-12-03",
    endDate: "2032-12-10",
  },
  {
    weekNumber: 48,
    year: 2033,
    startDate: "2033-12-09",
    endDate: "2033-12-16",
  },
  {
    weekNumber: 48,
    year: 2034,
    startDate: "2034-12-08",
    endDate: "2034-12-15",
  },
  {
    weekNumber: 48,
    year: 2035,
    startDate: "2035-12-07",
    endDate: "2035-12-14",
  },
  {
    weekNumber: 48,
    year: 2036,
    startDate: "2036-12-05",
    endDate: "2036-12-12",
  },
  {
    weekNumber: 48,
    year: 2037,
    startDate: "2037-12-04",
    endDate: "2037-12-11",
  },
  {
    weekNumber: 48,
    year: 2038,
    startDate: "2038-12-03",
    endDate: "2038-12-10",
  },
  {
    weekNumber: 48,
    year: 2039,
    startDate: "2039-12-09",
    endDate: "2039-12-16",
  },
  {
    weekNumber: 48,
    year: 2040,
    startDate: "2040-12-07",
    endDate: "2040-12-14",
  },
  {
    weekNumber: 49,
    year: 2025,
    startDate: "2025-12-12",
    endDate: "2025-12-19",
  },
  {
    weekNumber: 49,
    year: 2026,
    startDate: "2026-12-11",
    endDate: "2026-12-18",
  },
  {
    weekNumber: 49,
    year: 2027,
    startDate: "2027-12-10",
    endDate: "2027-12-17",
  },
  {
    weekNumber: 49,
    year: 2028,
    startDate: "2028-12-15",
    endDate: "2028-12-22",
  },
  {
    weekNumber: 49,
    year: 2029,
    startDate: "2029-12-14",
    endDate: "2029-12-21",
  },
  {
    weekNumber: 49,
    year: 2030,
    startDate: "2030-12-13",
    endDate: "2030-12-20",
  },
  {
    weekNumber: 49,
    year: 2031,
    startDate: "2031-12-12",
    endDate: "2031-12-19",
  },
  {
    weekNumber: 49,
    year: 2032,
    startDate: "2032-12-10",
    endDate: "2032-12-17",
  },
  {
    weekNumber: 49,
    year: 2033,
    startDate: "2033-12-16",
    endDate: "2033-12-23",
  },
  {
    weekNumber: 49,
    year: 2034,
    startDate: "2034-12-15",
    endDate: "2034-12-22",
  },
  {
    weekNumber: 49,
    year: 2035,
    startDate: "2035-12-14",
    endDate: "2035-12-21",
  },
  {
    weekNumber: 49,
    year: 2036,
    startDate: "2036-12-12",
    endDate: "2036-12-19",
  },
  {
    weekNumber: 49,
    year: 2037,
    startDate: "2037-12-11",
    endDate: "2037-12-18",
  },
  {
    weekNumber: 49,
    year: 2038,
    startDate: "2038-12-10",
    endDate: "2038-12-17",
  },
  {
    weekNumber: 49,
    year: 2039,
    startDate: "2039-12-16",
    endDate: "2039-12-23",
  },
  {
    weekNumber: 49,
    year: 2040,
    startDate: "2040-12-14",
    endDate: "2040-12-21",
  },
  {
    weekNumber: 50,
    year: 2025,
    startDate: "2025-12-19",
    endDate: "2025-12-26",
  },
  {
    weekNumber: 50,
    year: 2026,
    startDate: "2026-12-18",
    endDate: "2026-12-25",
  },
  {
    weekNumber: 50,
    year: 2027,
    startDate: "2027-12-17",
    endDate: "2027-12-24",
  },
  {
    weekNumber: 50,
    year: 2028,
    startDate: "2028-12-22",
    endDate: "2028-12-29",
  },
  {
    weekNumber: 50,
    year: 2029,
    startDate: "2029-12-21",
    endDate: "2029-12-28",
  },
  {
    weekNumber: 50,
    year: 2030,
    startDate: "2030-12-20",
    endDate: "2030-12-27",
  },
  {
    weekNumber: 50,
    year: 2031,
    startDate: "2031-12-19",
    endDate: "2031-12-26",
  },
  {
    weekNumber: 50,
    year: 2032,
    startDate: "2032-12-17",
    endDate: "2032-12-24",
  },
  {
    weekNumber: 50,
    year: 2033,
    startDate: "2033-12-23",
    endDate: "2033-12-30",
  },
  {
    weekNumber: 50,
    year: 2034,
    startDate: "2034-12-22",
    endDate: "2034-12-29",
  },
  {
    weekNumber: 50,
    year: 2035,
    startDate: "2035-12-21",
    endDate: "2035-12-28",
  },
  {
    weekNumber: 50,
    year: 2036,
    startDate: "2036-12-19",
    endDate: "2036-12-26",
  },
  {
    weekNumber: 50,
    year: 2037,
    startDate: "2037-12-18",
    endDate: "2037-12-25",
  },
  {
    weekNumber: 50,
    year: 2038,
    startDate: "2038-12-17",
    endDate: "2038-12-24",
  },
  {
    weekNumber: 50,
    year: 2039,
    startDate: "2039-12-23",
    endDate: "2039-12-30",
  },
  {
    weekNumber: 50,
    year: 2040,
    startDate: "2040-12-21",
    endDate: "2040-12-28",
  },
  {
    weekNumber: 51,
    year: 2025,
    startDate: "2025-12-26",
    endDate: "2026-01-02",
  },
  {
    weekNumber: 51,
    year: 2026,
    startDate: "2026-12-25",
    endDate: "2027-01-01",
  },
  {
    weekNumber: 51,
    year: 2027,
    startDate: "2027-12-24",
    endDate: "2027-12-31",
  },
  {
    weekNumber: 51,
    year: 2028,
    startDate: "2028-12-29",
    endDate: "2029-01-05",
  },
  {
    weekNumber: 51,
    year: 2029,
    startDate: "2029-12-28",
    endDate: "2030-01-04",
  },
  {
    weekNumber: 51,
    year: 2030,
    startDate: "2030-12-27",
    endDate: "2031-01-03",
  },
  {
    weekNumber: 51,
    year: 2031,
    startDate: "2031-12-26",
    endDate: "2032-01-02",
  },
  {
    weekNumber: 51,
    year: 2032,
    startDate: "2032-12-24",
    endDate: "2032-12-31",
  },
  {
    weekNumber: 51,
    year: 2033,
    startDate: "2033-12-30",
    endDate: "2034-01-06",
  },
  {
    weekNumber: 51,
    year: 2034,
    startDate: "2034-12-29",
    endDate: "2035-01-05",
  },
  {
    weekNumber: 51,
    year: 2035,
    startDate: "2035-12-28",
    endDate: "2036-01-04",
  },
  {
    weekNumber: 51,
    year: 2036,
    startDate: "2036-12-26",
    endDate: "2037-01-02",
  },
  {
    weekNumber: 51,
    year: 2037,
    startDate: "2037-12-25",
    endDate: "2038-01-01",
  },
  {
    weekNumber: 51,
    year: 2038,
    startDate: "2038-12-24",
    endDate: "2038-12-31",
  },
  {
    weekNumber: 51,
    year: 2039,
    startDate: "2039-12-30",
    endDate: "2040-01-06",
  },
  {
    weekNumber: 51,
    year: 2040,
    startDate: "2040-12-28",
    endDate: "2041-01-04",
  },
  {
    weekNumber: 52,
    year: 2025,
    startDate: "2026-01-02",
    endDate: "2026-01-09",
  },
  {
    weekNumber: 52,
    year: 2026,
    startDate: "2027-01-01",
    endDate: "2027-01-08",
  },
  {
    weekNumber: 52,
    year: 2027,
    startDate: "2027-12-31",
    endDate: "2028-01-07",
  },
  {
    weekNumber: 52,
    year: 2028,
    startDate: "2029-01-05",
    endDate: "2029-01-12",
  },
  {
    weekNumber: 52,
    year: 2029,
    startDate: "2030-01-04",
    endDate: "2030-01-11",
  },
  {
    weekNumber: 52,
    year: 2030,
    startDate: "2031-01-03",
    endDate: "2031-01-10",
  },
  {
    weekNumber: 52,
    year: 2031,
    startDate: "2032-01-02",
    endDate: "2032-01-09",
  },
  {
    weekNumber: 52,
    year: 2032,
    startDate: "2032-12-31",
    endDate: "2033-01-07",
  },
  {
    weekNumber: 52,
    year: 2033,
    startDate: "2034-01-06",
    endDate: "2034-01-13",
  },
  {
    weekNumber: 52,
    year: 2034,
    startDate: "2035-01-05",
    endDate: "2035-01-12",
  },
  {
    weekNumber: 52,
    year: 2035,
    startDate: "2036-01-04",
    endDate: "2036-01-11",
  },
  {
    weekNumber: 52,
    year: 2036,
    startDate: "2037-01-02",
    endDate: "2037-01-09",
  },
  {
    weekNumber: 52,
    year: 2037,
    startDate: "2038-01-01",
    endDate: "2038-01-08",
  },
  {
    weekNumber: 52,
    year: 2038,
    startDate: "2038-12-31",
    endDate: "2039-01-07",
  },
  {
    weekNumber: 52,
    year: 2039,
    startDate: "2040-01-06",
    endDate: "2040-01-13",
  },
  {
    weekNumber: 52,
    year: 2040,
    startDate: "2041-01-04",
    endDate: "2041-01-11",
  },
  {
    weekNumber: 53,
    year: 2027,
    startDate: "2028-01-07",
    endDate: "2028-01-14",
  },
  {
    weekNumber: 53,
    year: 2032,
    startDate: "2033-01-07",
    endDate: "2033-01-14",
  },
  {
    weekNumber: 53,
    year: 2038,
    startDate: "2039-01-07",
    endDate: "2039-01-14",
  },
];

/** Get the date range for a week number in a given year */
export function getWeekDates(
  weekNumber: number,
  year: number,
): WeekDate | undefined {
  return WEEK_CALENDAR.find(
    (w) => w.weekNumber === weekNumber && w.year === year,
  );
}

/** Get all week dates for a given year */
export function getWeeksForYear(year: number): WeekDate[] {
  return WEEK_CALENDAR.filter((w) => w.year === year).sort(
    (a, b) => a.weekNumber - b.weekNumber,
  );
}

/** Get available years */
// Derived, not a literal: the table now runs well past the hand-written
// [2026..2030] this used to hold.
export const AVAILABLE_YEARS = Array.from(
  new Set(WEEK_CALENDAR.map((w) => w.year)),
)
  .filter((y) => y >= new Date().getFullYear())
  .sort((a, b) => a - b);

/**
 * Week-years worth showing in the calendar, earliest first. A year whose last
 * week has already ended is dropped — owners look forward, not back.
 */
export function getCalendarYears(): number[] {
  const today = new Date().toISOString().slice(0, 10);
  const lastEnd = new Map<number, string>();
  for (const w of WEEK_CALENDAR) {
    const prev = lastEnd.get(w.year);
    if (!prev || w.endDate > prev) lastEnd.set(w.year, w.endDate);
  }
  return Array.from(lastEnd.entries())
    .filter(([, end]) => end >= today)
    .map(([year]) => year)
    .sort((a, b) => a - b);
}

/**
 * Which week does a calendar date fall in? Weeks run Friday noon to Friday,
 * so a date is "in" the week whose span contains it.
 */
export function findWeekForDate(date: string): WeekDate | null {
  return (
    WEEK_CALENDAR.find((w) => date >= w.startDate && date < w.endDate) ?? null
  );
}

/** Format a week date range for display: "Sep 11 – Sep 18, 2026" */
export function formatWeekRange(weekNumber: number, year: number): string {
  const wd = getWeekDates(weekNumber, year);
  if (!wd) return `Week ${weekNumber}`;
  const opts: Intl.DateTimeFormatOptions = { month: "short", day: "numeric" };
  const start = new Date(wd.startDate + "T12:00:00");
  const end = new Date(wd.endDate + "T12:00:00");
  const startStr = start.toLocaleDateString("en-US", opts);
  const endYear = end.getFullYear();
  const endOpts: Intl.DateTimeFormatOptions =
    endYear !== start.getFullYear()
      ? { month: "short", day: "numeric", year: "numeric" }
      : { month: "short", day: "numeric" };
  const endStr = end.toLocaleDateString("en-US", endOpts);
  return `${startStr} – ${endStr}, ${year}`;
}

/** Get all entries */
export function getAllWeekCalendar(): WeekDate[] {
  return WEEK_CALENDAR;
}

/**
 * Returns the next 52 full weeks from today.
 * Each entry includes the weekNumber plus the dates for its *next upcoming* occurrence.
 * Once the current week's end date has passed, it drops off and a new 52nd week is added.
 */
export function getNext52Weeks(): WeekDate[] {
  const today = new Date();
  today.setHours(12, 0, 0, 0);
  const todayISO = today.toISOString().split("T")[0];

  // Gather all future week entries (startDate >= today) across all years
  const futureWeeks = WEEK_CALENDAR.filter((w) => w.endDate >= todayISO) // week hasn't ended yet
    .sort((a, b) => a.startDate.localeCompare(b.startDate));

  // Deduplicate by weekNumber — keep earliest upcoming occurrence
  const seen = new Set<number>();
  const result: WeekDate[] = [];
  for (const w of futureWeeks) {
    if (seen.has(w.weekNumber)) continue;
    seen.add(w.weekNumber);
    result.push(w);
    if (result.length >= 52) break;
  }

  return result;
}

/**
 * The next time a given week number actually occurs.
 *
 * A week number is meaningless to most owners on its own — "Week 32" does not
 * tell you when to pack. Owners also think forward: once this year's week has
 * passed, the useful dates are next year's [scott, 2026-09-13]. Returns
 * undefined when the calendar has no entry (2030 is the last year we hold).
 */
export function getUpcomingWeekDates(
  weekNumber: number,
  fromYear?: number,
): WeekDate | undefined {
  const today = new Date();
  const startYear = fromYear ?? today.getFullYear();
  const candidates = WEEK_CALENDAR.filter(
    (w) => w.weekNumber === weekNumber && w.year >= startYear,
  ).sort((a, b) => a.year - b.year);

  // Compare against the end of the week: an owner is still "in" their week on
  // the Thursday, so it should not jump to next year mid-stay.
  const upcoming = candidates.find(
    (w) => new Date(w.endDate + "T12:00:00") >= today,
  );
  return upcoming ?? candidates[candidates.length - 1];
}

/**
 * "August 13-20, 2027" — the house format [scott, 2026-09-13].
 *
 * Full month name, no spaces around the dash, year once at the end. A week
 * that crosses a month boundary names both months ("December 31-January 7"),
 * and the year shown is the one the week ends in.
 */
export function formatOwnerWeekRange(weekNumber: number, year: number): string {
  const wd = getWeekDates(weekNumber, year);
  if (!wd) return "";
  const start = new Date(wd.startDate + "T12:00:00");
  const end = new Date(wd.endDate + "T12:00:00");
  const month = (d: Date) => d.toLocaleDateString("en-US", { month: "long" });
  const head =
    start.getMonth() === end.getMonth()
      ? `${month(start)} ${start.getDate()}-${end.getDate()}`
      : `${month(start)} ${start.getDate()}-${month(end)} ${end.getDate()}`;
  return `${head}, ${end.getFullYear()}`;
}

/** The next occurrence of a week, in the house format, or "" if unknown. */
export function formatUpcomingWeekRange(
  weekNumber: number,
  fromYear?: number,
): string {
  const wd = getUpcomingWeekDates(weekNumber, fromYear);
  if (!wd) return "";
  return formatOwnerWeekRange(wd.weekNumber, wd.year);
}

/**
 * The next full year of weeks, starting with the first week that has not begun.
 *
 * A trade is arranged forward, so the picker should open on the next week an
 * owner could actually trade into and run a year from there [scott,
 * 2026-09-13]. Deliberately keyed on startDate rather than endDate: the week
 * we are currently inside is not a "full week from today".
 *
 * Each entry carries its own year, which is what makes a rolling list possible
 * across a year boundary — week 3 in this list may well be next year's.
 */
export function getRollingYearWeeks(): WeekDate[] {
  const today = new Date();
  today.setHours(12, 0, 0, 0);
  const todayISO = today.toISOString().split("T")[0];

  const upcoming = WEEK_CALENDAR.filter((w) => w.startDate > todayISO).sort(
    (a, b) => a.startDate.localeCompare(b.startDate),
  );

  const seen = new Set<number>();
  const result: WeekDate[] = [];
  for (const w of upcoming) {
    if (seen.has(w.weekNumber)) continue;
    seen.add(w.weekNumber);
    result.push(w);
    if (result.length >= 52) break;
  }
  return result;
}

/** Years that still have at least one week left to trade into. */
/**
 * How many years ahead a trade may be requested.
 *
 * The calendar itself runs to 2040, but a trade is a one-time swap of a
 * specific week, so offering fifteen years in the picker is noise. Raise this
 * if owners actually ask to trade further out.
 */
export const TRADE_YEAR_HORIZON = 3;

export function getSelectableYears(): number[] {
  const today = new Date();
  const todayISO = today.toISOString().split("T")[0];
  const maxYear = today.getFullYear() + TRADE_YEAR_HORIZON;
  const years = new Set<number>();
  for (const w of WEEK_CALENDAR) {
    // Only weeks still to come, and only inside the trade horizon.
    if (w.startDate > todayISO && w.year <= maxYear) years.add(w.year);
  }
  return [...years].sort((a, b) => a - b);
}

/**
 * Weeks in a given year that have not started yet.
 *
 * The year is chosen first and the week list follows it, so the current year
 * offers only the weeks still to come — in September 2026 that is week 38
 * onward, not all 52 [scott, 2026-09-13]. A future year offers everything.
 */
export function getRemainingWeeksInYear(year: number): WeekDate[] {
  const todayISO = new Date().toISOString().split("T")[0];
  return WEEK_CALENDAR.filter(
    (w) => w.year === year && w.startDate > todayISO,
  ).sort((a, b) => a.weekNumber - b.weekNumber);
}
